//! GamificationChallenge trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::GamificationChallenge;

pub type GamificationChallengeTriggerEvent      = TriggerEvent;
pub type GamificationChallengeTriggerContext    = TriggerContext<GamificationChallenge>;
pub type GamificationChallengeTriggerContextMut = TriggerContextMut<GamificationChallenge>;
pub type GamificationChallengeActionExecutor    = ActionExecutor;
pub type GamificationChallengeTriggerRegistry   = TriggerRegistry<GamificationChallenge>;
pub type GamificationChallengeTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<GamificationChallenge>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for GamificationChallenge.
pub fn gamification_challenge_trigger_registry() -> GamificationChallengeTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
