//! EngagementLinkTrackerClick DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EngagementLinkTrackerClick;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EngagementLinkTrackerClick
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEngagementLinkTrackerClickDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "link_id")]
    pub link_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "click_day")]
    pub click_day: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "dedup_key")]
    pub dedup_key: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EngagementLinkTrackerClick
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEngagementLinkTrackerClickDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "link_id")]
    pub link_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "click_day")]
    pub click_day: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "dedup_key")]
    pub dedup_key: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EngagementLinkTrackerClick
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEngagementLinkTrackerClickDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "link_id")]
    pub link_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "click_day")]
    pub click_day: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "dedup_key")]
    pub dedup_key: Option<String>,
}

impl PatchEngagementLinkTrackerClickDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.link_id.is_some() || self.campaign_id.is_some() || self.ip.is_some() || self.country_code.is_some() || self.click_day.is_some() || self.dedup_key.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EngagementLinkTrackerClick entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementLinkTrackerClickResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub link_id: Uuid,
    pub campaign_id: Option<Uuid>,
    pub ip: Option<String>,
    pub country_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub click_day: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub dedup_key: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EngagementLinkTrackerClick entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementLinkTrackerClickListResponseDto {
    /// List of items
    pub items: Vec<EngagementLinkTrackerClickResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EngagementLinkTrackerClickListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EngagementLinkTrackerClickResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementLinkTrackerClickSummaryDto {
    pub id: Uuid,
    pub link_id: Uuid,
    pub campaign_id: Option<Uuid>,
    pub ip: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EngagementLinkTrackerClick> for EngagementLinkTrackerClickResponseDto {
    fn from(entity: EngagementLinkTrackerClick) -> Self {
        Self {
            id: entity.id,
            link_id: entity.link_id,
            campaign_id: entity.campaign_id,
            ip: entity.ip,
            country_code: entity.country_code,
            click_day: entity.click_day,
            dedup_key: entity.dedup_key,
            metadata: entity.metadata,
        }
    }
}

impl From<EngagementLinkTrackerClick> for EngagementLinkTrackerClickSummaryDto {
    fn from(entity: EngagementLinkTrackerClick) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            link_id: entity.link_id,
            campaign_id: entity.campaign_id,
            ip: entity.ip,
            created_at,
        }
    }
}

impl From<CreateEngagementLinkTrackerClickDto> for EngagementLinkTrackerClick {
    fn from(dto: CreateEngagementLinkTrackerClickDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            link_id: dto.link_id,
            campaign_id: dto.campaign_id,
            ip: dto.ip,
            country_code: dto.country_code,
            click_day: dto.click_day,
            dedup_key: dto.dedup_key,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EngagementLinkTrackerClick> for EngagementLinkTrackerClickResponseDto {
    fn from(entity: &EngagementLinkTrackerClick) -> Self {
        Self {
            id: entity.id.clone(),
            link_id: entity.link_id.clone(),
            campaign_id: entity.campaign_id.clone(),
            ip: entity.ip.clone(),
            country_code: entity.country_code.clone(),
            click_day: entity.click_day.clone(),
            dedup_key: entity.dedup_key.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEngagementLinkTrackerClickDto> for EngagementLinkTrackerClick {
    fn from_create_dto(dto: CreateEngagementLinkTrackerClickDto) -> backbone_core::ServiceResult<Self> {
        Ok(EngagementLinkTrackerClick::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEngagementLinkTrackerClickDto> for EngagementLinkTrackerClick {
    fn apply_update(mut self, dto: UpdateEngagementLinkTrackerClickDto) -> backbone_core::ServiceResult<Self> {
        self.link_id = dto.link_id;
        self.campaign_id = dto.campaign_id;
        self.ip = dto.ip;
        self.country_code = dto.country_code;
        self.click_day = dto.click_day;
        self.dedup_key = dto.dedup_key;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EngagementLinkTrackerClick here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
