//! EngagementCampaign DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EngagementCampaign;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EngagementCampaign
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEngagementCampaignDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_auto_campaign")]
    pub is_auto_campaign: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<i32>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EngagementCampaign
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEngagementCampaignDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_auto_campaign")]
    pub is_auto_campaign: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<i32>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EngagementCampaign
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEngagementCampaignDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_auto_campaign")]
    pub is_auto_campaign: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<i32>,
}

impl PatchEngagementCampaignDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.title.is_some() || self.active.is_some() || self.user_id.is_some() || self.is_auto_campaign.is_some() || self.color.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EngagementCampaign entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementCampaignResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_auto_campaign: bool,
    pub color: Option<i32>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EngagementCampaign entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementCampaignListResponseDto {
    /// List of items
    pub items: Vec<EngagementCampaignResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EngagementCampaignListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EngagementCampaignResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementCampaignSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub title: String,
    pub active: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EngagementCampaign> for EngagementCampaignResponseDto {
    fn from(entity: EngagementCampaign) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            title: entity.title,
            active: entity.active,
            user_id: entity.user_id,
            is_auto_campaign: entity.is_auto_campaign,
            color: entity.color,
            metadata: entity.metadata,
        }
    }
}

impl From<EngagementCampaign> for EngagementCampaignSummaryDto {
    fn from(entity: EngagementCampaign) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            title: entity.title,
            active: entity.active,
            created_at,
        }
    }
}

impl From<CreateEngagementCampaignDto> for EngagementCampaign {
    fn from(dto: CreateEngagementCampaignDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            title: dto.title,
            active: dto.active,
            user_id: dto.user_id,
            is_auto_campaign: dto.is_auto_campaign,
            color: dto.color,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EngagementCampaign> for EngagementCampaignResponseDto {
    fn from(entity: &EngagementCampaign) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            title: entity.title.clone(),
            active: entity.active.clone(),
            user_id: entity.user_id.clone(),
            is_auto_campaign: entity.is_auto_campaign.clone(),
            color: entity.color.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEngagementCampaignDto> for EngagementCampaign {
    fn from_create_dto(dto: CreateEngagementCampaignDto) -> backbone_core::ServiceResult<Self> {
        Ok(EngagementCampaign::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEngagementCampaignDto> for EngagementCampaign {
    fn apply_update(mut self, dto: UpdateEngagementCampaignDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.title = dto.title;
        self.active = dto.active;
        self.user_id = dto.user_id;
        self.is_auto_campaign = dto.is_auto_campaign;
        self.color = dto.color;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EngagementCampaign here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
