//! EngagementLinkTracker DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EngagementLinkTracker;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EngagementLinkTracker
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEngagementLinkTrackerDto {
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "medium_id")]
    pub medium_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_id")]
    pub source_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EngagementLinkTracker
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEngagementLinkTrackerDto {
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "medium_id")]
    pub medium_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_id")]
    pub source_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EngagementLinkTracker
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEngagementLinkTrackerDto {
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "medium_id")]
    pub medium_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_id")]
    pub source_id: Option<Uuid>,
}

impl PatchEngagementLinkTrackerDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.url.is_some() || self.code.is_some() || self.title.is_some() || self.label.is_some() || self.campaign_id.is_some() || self.medium_id.is_some() || self.source_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EngagementLinkTracker entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementLinkTrackerResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub url: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    pub title: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    pub campaign_id: Option<Uuid>,
    pub medium_id: Option<Uuid>,
    pub source_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EngagementLinkTracker entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementLinkTrackerListResponseDto {
    /// List of items
    pub items: Vec<EngagementLinkTrackerResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EngagementLinkTrackerListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EngagementLinkTrackerResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EngagementLinkTrackerSummaryDto {
    pub id: Uuid,
    pub url: String,
    pub code: String,
    pub title: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EngagementLinkTracker> for EngagementLinkTrackerResponseDto {
    fn from(entity: EngagementLinkTracker) -> Self {
        Self {
            id: entity.id,
            url: entity.url,
            code: entity.code,
            title: entity.title,
            label: entity.label,
            campaign_id: entity.campaign_id,
            medium_id: entity.medium_id,
            source_id: entity.source_id,
            metadata: entity.metadata,
        }
    }
}

impl From<EngagementLinkTracker> for EngagementLinkTrackerSummaryDto {
    fn from(entity: EngagementLinkTracker) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            url: entity.url,
            code: entity.code,
            title: entity.title,
            created_at,
        }
    }
}

impl From<CreateEngagementLinkTrackerDto> for EngagementLinkTracker {
    fn from(dto: CreateEngagementLinkTrackerDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            url: dto.url,
            code: dto.code,
            title: dto.title,
            label: dto.label,
            campaign_id: dto.campaign_id,
            medium_id: dto.medium_id,
            source_id: dto.source_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EngagementLinkTracker> for EngagementLinkTrackerResponseDto {
    fn from(entity: &EngagementLinkTracker) -> Self {
        Self {
            id: entity.id.clone(),
            url: entity.url.clone(),
            code: entity.code.clone(),
            title: entity.title.clone(),
            label: entity.label.clone(),
            campaign_id: entity.campaign_id.clone(),
            medium_id: entity.medium_id.clone(),
            source_id: entity.source_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEngagementLinkTrackerDto> for EngagementLinkTracker {
    fn from_create_dto(dto: CreateEngagementLinkTrackerDto) -> backbone_core::ServiceResult<Self> {
        Ok(EngagementLinkTracker::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEngagementLinkTrackerDto> for EngagementLinkTracker {
    fn apply_update(mut self, dto: UpdateEngagementLinkTrackerDto) -> backbone_core::ServiceResult<Self> {
        self.url = dto.url;
        self.code = dto.code;
        self.title = dto.title;
        self.label = dto.label;
        self.campaign_id = dto.campaign_id;
        self.medium_id = dto.medium_id;
        self.source_id = dto.source_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EngagementLinkTracker here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
