//! GamificationChallenge DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::GamificationChallenge;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ChallengePeriod;
use crate::domain::entity::ChallengeState;
use crate::domain::entity::ChallengeVisibilityMode;
use crate::domain::entity::ReportFrequency;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new GamificationChallenge
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGamificationChallengeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub state: ChallengeState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "manager_user_id")]
    pub manager_user_id: Option<Uuid>,
    pub period: ChallengePeriod,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(alias = "visibility_mode")]
    pub visibility_mode: ChallengeVisibilityMode,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_badge_id")]
    pub reward_badge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_first_badge_id")]
    pub reward_first_badge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_second_badge_id")]
    pub reward_second_badge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_third_badge_id")]
    pub reward_third_badge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "reward_failure")]
    pub reward_failure: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "reward_realtime")]
    pub reward_realtime: bool,
    #[serde(alias = "report_frequency")]
    pub report_frequency: ReportFrequency,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_report_date")]
    pub last_report_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "next_report_date")]
    pub next_report_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "remind_update_delay")]
    pub remind_update_delay: Option<i32>,
    #[serde(alias = "user_ids")]
    pub user_ids: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "include_all_users")]
    pub include_all_users: bool,
    #[serde(alias = "include_badge_ids")]
    pub include_badge_ids: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a GamificationChallenge
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGamificationChallengeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub state: ChallengeState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "manager_user_id")]
    pub manager_user_id: Option<Uuid>,
    pub period: ChallengePeriod,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(alias = "visibility_mode")]
    pub visibility_mode: ChallengeVisibilityMode,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_badge_id")]
    pub reward_badge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_first_badge_id")]
    pub reward_first_badge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_second_badge_id")]
    pub reward_second_badge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_third_badge_id")]
    pub reward_third_badge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "reward_failure")]
    pub reward_failure: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "reward_realtime")]
    pub reward_realtime: bool,
    #[serde(alias = "report_frequency")]
    pub report_frequency: ReportFrequency,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_report_date")]
    pub last_report_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "next_report_date")]
    pub next_report_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "remind_update_delay")]
    pub remind_update_delay: Option<i32>,
    #[serde(alias = "user_ids")]
    pub user_ids: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "include_all_users")]
    pub include_all_users: bool,
    #[serde(alias = "include_badge_ids")]
    pub include_badge_ids: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a GamificationChallenge
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGamificationChallengeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<ChallengeState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "manager_user_id")]
    pub manager_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<ChallengePeriod>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "visibility_mode")]
    pub visibility_mode: Option<ChallengeVisibilityMode>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_badge_id")]
    pub reward_badge_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_first_badge_id")]
    pub reward_first_badge_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_second_badge_id")]
    pub reward_second_badge_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_third_badge_id")]
    pub reward_third_badge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_failure")]
    pub reward_failure: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_realtime")]
    pub reward_realtime: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "report_frequency")]
    pub report_frequency: Option<ReportFrequency>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_report_date")]
    pub last_report_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "next_report_date")]
    pub next_report_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "remind_update_delay")]
    pub remind_update_delay: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_ids")]
    pub user_ids: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "include_all_users")]
    pub include_all_users: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "include_badge_ids")]
    pub include_badge_ids: Option<serde_json::Value>,
}

impl PatchGamificationChallengeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.state.is_some() || self.manager_user_id.is_some() || self.period.is_some() || self.start_date.is_some() || self.end_date.is_some() || self.visibility_mode.is_some() || self.reward_badge_id.is_some() || self.reward_first_badge_id.is_some() || self.reward_second_badge_id.is_some() || self.reward_third_badge_id.is_some() || self.reward_failure.is_some() || self.reward_realtime.is_some() || self.report_frequency.is_some() || self.last_report_date.is_some() || self.next_report_date.is_some() || self.remind_update_delay.is_some() || self.user_ids.is_some() || self.include_all_users.is_some() || self.include_badge_ids.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for GamificationChallenge entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationChallengeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub state: ChallengeState,
    pub manager_user_id: Option<Uuid>,
    pub period: ChallengePeriod,
    pub start_date: Option<NaiveDate>,
    pub end_date: Option<NaiveDate>,
    pub visibility_mode: ChallengeVisibilityMode,
    pub reward_badge_id: Option<Uuid>,
    pub reward_first_badge_id: Option<Uuid>,
    pub reward_second_badge_id: Option<Uuid>,
    pub reward_third_badge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub reward_failure: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub reward_realtime: bool,
    pub report_frequency: ReportFrequency,
    pub last_report_date: Option<NaiveDate>,
    pub next_report_date: Option<NaiveDate>,
    pub remind_update_delay: Option<i32>,
    pub user_ids: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub include_all_users: bool,
    pub include_badge_ids: serde_json::Value,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for GamificationChallenge entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationChallengeListResponseDto {
    /// List of items
    pub items: Vec<GamificationChallengeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GamificationChallengeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GamificationChallengeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationChallengeSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub state: ChallengeState,
    pub manager_user_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<GamificationChallenge> for GamificationChallengeResponseDto {
    fn from(entity: GamificationChallenge) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            state: entity.state,
            manager_user_id: entity.manager_user_id,
            period: entity.period,
            start_date: entity.start_date,
            end_date: entity.end_date,
            visibility_mode: entity.visibility_mode,
            reward_badge_id: entity.reward_badge_id,
            reward_first_badge_id: entity.reward_first_badge_id,
            reward_second_badge_id: entity.reward_second_badge_id,
            reward_third_badge_id: entity.reward_third_badge_id,
            reward_failure: entity.reward_failure,
            reward_realtime: entity.reward_realtime,
            report_frequency: entity.report_frequency,
            last_report_date: entity.last_report_date,
            next_report_date: entity.next_report_date,
            remind_update_delay: entity.remind_update_delay,
            user_ids: entity.user_ids,
            include_all_users: entity.include_all_users,
            include_badge_ids: entity.include_badge_ids,
            metadata: entity.metadata,
        }
    }
}

impl From<GamificationChallenge> for GamificationChallengeSummaryDto {
    fn from(entity: GamificationChallenge) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            state: entity.state,
            manager_user_id: entity.manager_user_id,
            created_at,
        }
    }
}

impl From<CreateGamificationChallengeDto> for GamificationChallenge {
    fn from(dto: CreateGamificationChallengeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            state: dto.state,
            manager_user_id: dto.manager_user_id,
            period: dto.period,
            start_date: dto.start_date,
            end_date: dto.end_date,
            visibility_mode: dto.visibility_mode,
            reward_badge_id: dto.reward_badge_id,
            reward_first_badge_id: dto.reward_first_badge_id,
            reward_second_badge_id: dto.reward_second_badge_id,
            reward_third_badge_id: dto.reward_third_badge_id,
            reward_failure: dto.reward_failure,
            reward_realtime: dto.reward_realtime,
            report_frequency: dto.report_frequency,
            last_report_date: dto.last_report_date,
            next_report_date: dto.next_report_date,
            remind_update_delay: dto.remind_update_delay,
            user_ids: dto.user_ids,
            include_all_users: dto.include_all_users,
            include_badge_ids: dto.include_badge_ids,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&GamificationChallenge> for GamificationChallengeResponseDto {
    fn from(entity: &GamificationChallenge) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            state: entity.state.clone(),
            manager_user_id: entity.manager_user_id.clone(),
            period: entity.period.clone(),
            start_date: entity.start_date.clone(),
            end_date: entity.end_date.clone(),
            visibility_mode: entity.visibility_mode.clone(),
            reward_badge_id: entity.reward_badge_id.clone(),
            reward_first_badge_id: entity.reward_first_badge_id.clone(),
            reward_second_badge_id: entity.reward_second_badge_id.clone(),
            reward_third_badge_id: entity.reward_third_badge_id.clone(),
            reward_failure: entity.reward_failure.clone(),
            reward_realtime: entity.reward_realtime.clone(),
            report_frequency: entity.report_frequency.clone(),
            last_report_date: entity.last_report_date.clone(),
            next_report_date: entity.next_report_date.clone(),
            remind_update_delay: entity.remind_update_delay.clone(),
            user_ids: entity.user_ids.clone(),
            include_all_users: entity.include_all_users.clone(),
            include_badge_ids: entity.include_badge_ids.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGamificationChallengeDto> for GamificationChallenge {
    fn from_create_dto(dto: CreateGamificationChallengeDto) -> backbone_core::ServiceResult<Self> {
        Ok(GamificationChallenge::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGamificationChallengeDto> for GamificationChallenge {
    fn apply_update(mut self, dto: UpdateGamificationChallengeDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.state = dto.state;
        self.manager_user_id = dto.manager_user_id;
        self.period = dto.period;
        self.start_date = dto.start_date;
        self.end_date = dto.end_date;
        self.visibility_mode = dto.visibility_mode;
        self.reward_badge_id = dto.reward_badge_id;
        self.reward_first_badge_id = dto.reward_first_badge_id;
        self.reward_second_badge_id = dto.reward_second_badge_id;
        self.reward_third_badge_id = dto.reward_third_badge_id;
        self.reward_failure = dto.reward_failure;
        self.reward_realtime = dto.reward_realtime;
        self.report_frequency = dto.report_frequency;
        self.last_report_date = dto.last_report_date;
        self.next_report_date = dto.next_report_date;
        self.remind_update_delay = dto.remind_update_delay;
        self.user_ids = dto.user_ids;
        self.include_all_users = dto.include_all_users;
        self.include_badge_ids = dto.include_badge_ids;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to GamificationChallenge here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
