//! GamificationBadgeUser DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::GamificationBadgeUser;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BadgeGrantKind;
use crate::domain::entity::BadgeLevel;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new GamificationBadgeUser
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGamificationBadgeUserDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "badge_id")]
    pub badge_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "recipient_user_id")]
    pub recipient_user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sender_user_id")]
    pub sender_user_id: Option<Uuid>,
    #[serde(alias = "grant_kind")]
    pub grant_kind: BadgeGrantKind,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "challenge_id")]
    pub challenge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub level: Option<BadgeLevel>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "granted_at")]
    pub granted_at: DateTime<Utc>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "grant_key")]
    pub grant_key: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a GamificationBadgeUser
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGamificationBadgeUserDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "badge_id")]
    pub badge_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "recipient_user_id")]
    pub recipient_user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sender_user_id")]
    pub sender_user_id: Option<Uuid>,
    #[serde(alias = "grant_kind")]
    pub grant_kind: BadgeGrantKind,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "challenge_id")]
    pub challenge_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub level: Option<BadgeLevel>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "granted_at")]
    pub granted_at: DateTime<Utc>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "grant_key")]
    pub grant_key: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a GamificationBadgeUser
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGamificationBadgeUserDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "badge_id")]
    pub badge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "recipient_user_id")]
    pub recipient_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sender_user_id")]
    pub sender_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "grant_kind")]
    pub grant_kind: Option<BadgeGrantKind>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "challenge_id")]
    pub challenge_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<BadgeLevel>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "granted_at")]
    pub granted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "grant_key")]
    pub grant_key: Option<String>,
}

impl PatchGamificationBadgeUserDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.badge_id.is_some() || self.recipient_user_id.is_some() || self.sender_user_id.is_some() || self.grant_kind.is_some() || self.challenge_id.is_some() || self.comment.is_some() || self.level.is_some() || self.granted_at.is_some() || self.grant_key.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for GamificationBadgeUser entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationBadgeUserResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub badge_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub recipient_user_id: Uuid,
    pub sender_user_id: Option<Uuid>,
    pub grant_kind: BadgeGrantKind,
    pub challenge_id: Option<Uuid>,
    pub comment: Option<String>,
    pub level: Option<BadgeLevel>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub granted_at: DateTime<Utc>,
    pub grant_key: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for GamificationBadgeUser entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationBadgeUserListResponseDto {
    /// List of items
    pub items: Vec<GamificationBadgeUserResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GamificationBadgeUserListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GamificationBadgeUserResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationBadgeUserSummaryDto {
    pub id: Uuid,
    pub badge_id: Uuid,
    pub recipient_user_id: Uuid,
    pub sender_user_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<GamificationBadgeUser> for GamificationBadgeUserResponseDto {
    fn from(entity: GamificationBadgeUser) -> Self {
        Self {
            id: entity.id,
            badge_id: entity.badge_id,
            recipient_user_id: entity.recipient_user_id,
            sender_user_id: entity.sender_user_id,
            grant_kind: entity.grant_kind,
            challenge_id: entity.challenge_id,
            comment: entity.comment,
            level: entity.level,
            granted_at: entity.granted_at,
            grant_key: entity.grant_key,
            metadata: entity.metadata,
        }
    }
}

impl From<GamificationBadgeUser> for GamificationBadgeUserSummaryDto {
    fn from(entity: GamificationBadgeUser) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            badge_id: entity.badge_id,
            recipient_user_id: entity.recipient_user_id,
            sender_user_id: entity.sender_user_id,
            created_at,
        }
    }
}

impl From<CreateGamificationBadgeUserDto> for GamificationBadgeUser {
    fn from(dto: CreateGamificationBadgeUserDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            badge_id: dto.badge_id,
            recipient_user_id: dto.recipient_user_id,
            sender_user_id: dto.sender_user_id,
            grant_kind: dto.grant_kind,
            challenge_id: dto.challenge_id,
            comment: dto.comment,
            level: dto.level,
            granted_at: dto.granted_at,
            grant_key: dto.grant_key,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&GamificationBadgeUser> for GamificationBadgeUserResponseDto {
    fn from(entity: &GamificationBadgeUser) -> Self {
        Self {
            id: entity.id.clone(),
            badge_id: entity.badge_id.clone(),
            recipient_user_id: entity.recipient_user_id.clone(),
            sender_user_id: entity.sender_user_id.clone(),
            grant_kind: entity.grant_kind.clone(),
            challenge_id: entity.challenge_id.clone(),
            comment: entity.comment.clone(),
            level: entity.level.clone(),
            granted_at: entity.granted_at.clone(),
            grant_key: entity.grant_key.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGamificationBadgeUserDto> for GamificationBadgeUser {
    fn from_create_dto(dto: CreateGamificationBadgeUserDto) -> backbone_core::ServiceResult<Self> {
        Ok(GamificationBadgeUser::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGamificationBadgeUserDto> for GamificationBadgeUser {
    fn apply_update(mut self, dto: UpdateGamificationBadgeUserDto) -> backbone_core::ServiceResult<Self> {
        self.badge_id = dto.badge_id;
        self.recipient_user_id = dto.recipient_user_id;
        self.sender_user_id = dto.sender_user_id;
        self.grant_kind = dto.grant_kind;
        self.challenge_id = dto.challenge_id;
        self.comment = dto.comment;
        self.level = dto.level;
        self.granted_at = dto.granted_at;
        self.grant_key = dto.grant_key;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to GamificationBadgeUser here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
