//! GamificationGoal DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::GamificationGoal;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::GoalState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new GamificationGoal
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGamificationGoalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "definition_id")]
    pub definition_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "line_id")]
    pub line_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "challenge_id")]
    pub challenge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "start_date")]
    pub start_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    pub target: Decimal,
    pub current: Decimal,
    pub state: GoalState,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "to_update")]
    pub to_update: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_update")]
    pub last_update: Option<NaiveDate>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a GamificationGoal
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGamificationGoalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "definition_id")]
    pub definition_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "line_id")]
    pub line_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "challenge_id")]
    pub challenge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "start_date")]
    pub start_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    pub target: Decimal,
    pub current: Decimal,
    pub state: GoalState,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "to_update")]
    pub to_update: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_update")]
    pub last_update: Option<NaiveDate>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a GamificationGoal
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGamificationGoalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "definition_id")]
    pub definition_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "line_id")]
    pub line_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "challenge_id")]
    pub challenge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<GoalState>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_update")]
    pub to_update: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_update")]
    pub last_update: Option<NaiveDate>,
}

impl PatchGamificationGoalDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.definition_id.is_some() || self.user_id.is_some() || self.line_id.is_some() || self.challenge_id.is_some() || self.start_date.is_some() || self.end_date.is_some() || self.target.is_some() || self.current.is_some() || self.state.is_some() || self.to_update.is_some() || self.last_update.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for GamificationGoal entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationGoalResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub definition_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub line_id: Option<Uuid>,
    pub challenge_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub start_date: NaiveDate,
    pub end_date: Option<NaiveDate>,
    pub target: Decimal,
    pub current: Decimal,
    pub state: GoalState,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub to_update: bool,
    pub last_update: Option<NaiveDate>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for GamificationGoal entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationGoalListResponseDto {
    /// List of items
    pub items: Vec<GamificationGoalResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GamificationGoalListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GamificationGoalResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationGoalSummaryDto {
    pub id: Uuid,
    pub definition_id: Uuid,
    pub user_id: Uuid,
    pub line_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<GamificationGoal> for GamificationGoalResponseDto {
    fn from(entity: GamificationGoal) -> Self {
        Self {
            id: entity.id,
            definition_id: entity.definition_id,
            user_id: entity.user_id,
            line_id: entity.line_id,
            challenge_id: entity.challenge_id,
            start_date: entity.start_date,
            end_date: entity.end_date,
            target: entity.target,
            current: entity.current,
            state: entity.state,
            to_update: entity.to_update,
            last_update: entity.last_update,
            metadata: entity.metadata,
        }
    }
}

impl From<GamificationGoal> for GamificationGoalSummaryDto {
    fn from(entity: GamificationGoal) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            definition_id: entity.definition_id,
            user_id: entity.user_id,
            line_id: entity.line_id,
            created_at,
        }
    }
}

impl From<CreateGamificationGoalDto> for GamificationGoal {
    fn from(dto: CreateGamificationGoalDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            definition_id: dto.definition_id,
            user_id: dto.user_id,
            line_id: dto.line_id,
            challenge_id: dto.challenge_id,
            start_date: dto.start_date,
            end_date: dto.end_date,
            target: dto.target,
            current: dto.current,
            state: dto.state,
            to_update: dto.to_update,
            last_update: dto.last_update,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&GamificationGoal> for GamificationGoalResponseDto {
    fn from(entity: &GamificationGoal) -> Self {
        Self {
            id: entity.id.clone(),
            definition_id: entity.definition_id.clone(),
            user_id: entity.user_id.clone(),
            line_id: entity.line_id.clone(),
            challenge_id: entity.challenge_id.clone(),
            start_date: entity.start_date.clone(),
            end_date: entity.end_date.clone(),
            target: entity.target.clone(),
            current: entity.current.clone(),
            state: entity.state.clone(),
            to_update: entity.to_update.clone(),
            last_update: entity.last_update.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGamificationGoalDto> for GamificationGoal {
    fn from_create_dto(dto: CreateGamificationGoalDto) -> backbone_core::ServiceResult<Self> {
        Ok(GamificationGoal::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGamificationGoalDto> for GamificationGoal {
    fn apply_update(mut self, dto: UpdateGamificationGoalDto) -> backbone_core::ServiceResult<Self> {
        self.definition_id = dto.definition_id;
        self.user_id = dto.user_id;
        self.line_id = dto.line_id;
        self.challenge_id = dto.challenge_id;
        self.start_date = dto.start_date;
        self.end_date = dto.end_date;
        self.target = dto.target;
        self.current = dto.current;
        self.state = dto.state;
        self.to_update = dto.to_update;
        self.last_update = dto.last_update;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to GamificationGoal here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
