//! GamificationBadge DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::GamificationBadge;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BadgeLevel;
use crate::domain::entity::BadgeRuleAuth;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new GamificationBadge
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGamificationBadgeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub level: Option<BadgeLevel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(alias = "rule_auth")]
    pub rule_auth: BadgeRuleAuth,
    #[serde(alias = "rule_auth_user_ids")]
    pub rule_auth_user_ids: serde_json::Value,
    #[serde(alias = "rule_auth_badge_ids")]
    pub rule_auth_badge_ids: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "rule_max")]
    pub rule_max: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "rule_max_number")]
    pub rule_max_number: Option<i32>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a GamificationBadge
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGamificationBadgeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub level: Option<BadgeLevel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(alias = "rule_auth")]
    pub rule_auth: BadgeRuleAuth,
    #[serde(alias = "rule_auth_user_ids")]
    pub rule_auth_user_ids: serde_json::Value,
    #[serde(alias = "rule_auth_badge_ids")]
    pub rule_auth_badge_ids: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "rule_max")]
    pub rule_max: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "rule_max_number")]
    pub rule_max_number: Option<i32>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a GamificationBadge
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGamificationBadgeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<BadgeLevel>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rule_auth")]
    pub rule_auth: Option<BadgeRuleAuth>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rule_auth_user_ids")]
    pub rule_auth_user_ids: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rule_auth_badge_ids")]
    pub rule_auth_badge_ids: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "rule_max")]
    pub rule_max: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rule_max_number")]
    pub rule_max_number: Option<i32>,
}

impl PatchGamificationBadgeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.active.is_some() || self.level.is_some() || self.description.is_some() || self.rule_auth.is_some() || self.rule_auth_user_ids.is_some() || self.rule_auth_badge_ids.is_some() || self.rule_max.is_some() || self.rule_max_number.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for GamificationBadge entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationBadgeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub level: Option<BadgeLevel>,
    pub description: Option<String>,
    pub rule_auth: BadgeRuleAuth,
    pub rule_auth_user_ids: serde_json::Value,
    pub rule_auth_badge_ids: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub rule_max: bool,
    pub rule_max_number: Option<i32>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for GamificationBadge entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationBadgeListResponseDto {
    /// List of items
    pub items: Vec<GamificationBadgeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GamificationBadgeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GamificationBadgeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationBadgeSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub active: bool,
    pub level: Option<BadgeLevel>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<GamificationBadge> for GamificationBadgeResponseDto {
    fn from(entity: GamificationBadge) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            active: entity.active,
            level: entity.level,
            description: entity.description,
            rule_auth: entity.rule_auth,
            rule_auth_user_ids: entity.rule_auth_user_ids,
            rule_auth_badge_ids: entity.rule_auth_badge_ids,
            rule_max: entity.rule_max,
            rule_max_number: entity.rule_max_number,
            metadata: entity.metadata,
        }
    }
}

impl From<GamificationBadge> for GamificationBadgeSummaryDto {
    fn from(entity: GamificationBadge) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            active: entity.active,
            level: entity.level,
            created_at,
        }
    }
}

impl From<CreateGamificationBadgeDto> for GamificationBadge {
    fn from(dto: CreateGamificationBadgeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            active: dto.active,
            level: dto.level,
            description: dto.description,
            rule_auth: dto.rule_auth,
            rule_auth_user_ids: dto.rule_auth_user_ids,
            rule_auth_badge_ids: dto.rule_auth_badge_ids,
            rule_max: dto.rule_max,
            rule_max_number: dto.rule_max_number,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&GamificationBadge> for GamificationBadgeResponseDto {
    fn from(entity: &GamificationBadge) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            active: entity.active.clone(),
            level: entity.level.clone(),
            description: entity.description.clone(),
            rule_auth: entity.rule_auth.clone(),
            rule_auth_user_ids: entity.rule_auth_user_ids.clone(),
            rule_auth_badge_ids: entity.rule_auth_badge_ids.clone(),
            rule_max: entity.rule_max.clone(),
            rule_max_number: entity.rule_max_number.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGamificationBadgeDto> for GamificationBadge {
    fn from_create_dto(dto: CreateGamificationBadgeDto) -> backbone_core::ServiceResult<Self> {
        Ok(GamificationBadge::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGamificationBadgeDto> for GamificationBadge {
    fn apply_update(mut self, dto: UpdateGamificationBadgeDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.active = dto.active;
        self.level = dto.level;
        self.description = dto.description;
        self.rule_auth = dto.rule_auth;
        self.rule_auth_user_ids = dto.rule_auth_user_ids;
        self.rule_auth_badge_ids = dto.rule_auth_badge_ids;
        self.rule_max = dto.rule_max;
        self.rule_max_number = dto.rule_max_number;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to GamificationBadge here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
