//! GamificationKarmaTracking DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::GamificationKarmaTracking;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new GamificationKarmaTracking
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGamificationKarmaTrackingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "old_value")]
    pub old_value: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "new_value")]
    pub new_value: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "tracking_date")]
    pub tracking_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "origin_kind")]
    pub origin_kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "origin_id")]
    pub origin_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "origin_label")]
    pub origin_label: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a GamificationKarmaTracking
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGamificationKarmaTrackingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "old_value")]
    pub old_value: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "new_value")]
    pub new_value: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "tracking_date")]
    pub tracking_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "origin_kind")]
    pub origin_kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "origin_id")]
    pub origin_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "origin_label")]
    pub origin_label: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a GamificationKarmaTracking
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGamificationKarmaTrackingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "old_value")]
    pub old_value: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "new_value")]
    pub new_value: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "tracking_date")]
    pub tracking_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "origin_kind")]
    pub origin_kind: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "origin_id")]
    pub origin_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "origin_label")]
    pub origin_label: Option<String>,
}

impl PatchGamificationKarmaTrackingDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_id.is_some() || self.old_value.is_some() || self.new_value.is_some() || self.tracking_date.is_some() || self.reason.is_some() || self.origin_kind.is_some() || self.origin_id.is_some() || self.origin_label.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for GamificationKarmaTracking entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationKarmaTrackingResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub old_value: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub new_value: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub tracking_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub origin_kind: String,
    pub origin_id: Option<Uuid>,
    pub origin_label: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for GamificationKarmaTracking entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationKarmaTrackingListResponseDto {
    /// List of items
    pub items: Vec<GamificationKarmaTrackingResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GamificationKarmaTrackingListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GamificationKarmaTrackingResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GamificationKarmaTrackingSummaryDto {
    pub id: Uuid,
    pub user_id: Uuid,
    pub old_value: i32,
    pub new_value: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<GamificationKarmaTracking> for GamificationKarmaTrackingResponseDto {
    fn from(entity: GamificationKarmaTracking) -> Self {
        Self {
            id: entity.id,
            user_id: entity.user_id,
            old_value: entity.old_value,
            new_value: entity.new_value,
            tracking_date: entity.tracking_date,
            reason: entity.reason,
            origin_kind: entity.origin_kind,
            origin_id: entity.origin_id,
            origin_label: entity.origin_label,
            metadata: entity.metadata,
        }
    }
}

impl From<GamificationKarmaTracking> for GamificationKarmaTrackingSummaryDto {
    fn from(entity: GamificationKarmaTracking) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_id: entity.user_id,
            old_value: entity.old_value,
            new_value: entity.new_value,
            created_at,
        }
    }
}

impl From<CreateGamificationKarmaTrackingDto> for GamificationKarmaTracking {
    fn from(dto: CreateGamificationKarmaTrackingDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_id: dto.user_id,
            old_value: dto.old_value,
            new_value: dto.new_value,
            tracking_date: dto.tracking_date,
            reason: dto.reason,
            origin_kind: dto.origin_kind,
            origin_id: dto.origin_id,
            origin_label: dto.origin_label,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&GamificationKarmaTracking> for GamificationKarmaTrackingResponseDto {
    fn from(entity: &GamificationKarmaTracking) -> Self {
        Self {
            id: entity.id.clone(),
            user_id: entity.user_id.clone(),
            old_value: entity.old_value.clone(),
            new_value: entity.new_value.clone(),
            tracking_date: entity.tracking_date.clone(),
            reason: entity.reason.clone(),
            origin_kind: entity.origin_kind.clone(),
            origin_id: entity.origin_id.clone(),
            origin_label: entity.origin_label.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGamificationKarmaTrackingDto> for GamificationKarmaTracking {
    fn from_create_dto(dto: CreateGamificationKarmaTrackingDto) -> backbone_core::ServiceResult<Self> {
        Ok(GamificationKarmaTracking::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGamificationKarmaTrackingDto> for GamificationKarmaTracking {
    fn apply_update(mut self, dto: UpdateGamificationKarmaTrackingDto) -> backbone_core::ServiceResult<Self> {
        self.user_id = dto.user_id;
        self.old_value = dto.old_value;
        self.new_value = dto.new_value;
        self.tracking_date = dto.tracking_date;
        self.reason = dto.reason;
        self.origin_kind = dto.origin_kind;
        self.origin_id = dto.origin_id;
        self.origin_label = dto.origin_label;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to GamificationKarmaTracking here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
