//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod engagement_link_tracker_specification;
pub mod engagement_link_tracker_click_specification;
pub mod engagement_campaign_specification;
pub mod engagement_source_specification;
pub mod engagement_medium_specification;

// <<< CUSTOM
// END CUSTOM
