//! Application service for EngagementSource entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `engagement_source_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEngagementSourceDto, UpdateEngagementSourceDto};
use crate::domain::entity::EngagementSource;
use crate::infrastructure::persistence::EngagementSourceRepository;

/// Application service for EngagementSource entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `engagement_source_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EngagementSourceServiceCustom {
///     inner: Arc<EngagementSourceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EngagementSourceService = GenericCrudService<
    EngagementSource,
    CreateEngagementSourceDto,
    UpdateEngagementSourceDto,
    EngagementSourceRepository,
>;

// <<< CUSTOM
// END CUSTOM
