//! Application service for EngagementRating entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `engagement_rating_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEngagementRatingDto, UpdateEngagementRatingDto};
use crate::domain::entity::EngagementRating;
use crate::infrastructure::persistence::EngagementRatingRepository;

/// Application service for EngagementRating entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `engagement_rating_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EngagementRatingServiceCustom {
///     inner: Arc<EngagementRatingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EngagementRatingService = GenericCrudService<
    EngagementRating,
    CreateEngagementRatingDto,
    UpdateEngagementRatingDto,
    EngagementRatingRepository,
>;

// <<< CUSTOM
// END CUSTOM
