//! Application service for EngagementLinkTrackerClick entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `engagement_link_tracker_click_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEngagementLinkTrackerClickDto, UpdateEngagementLinkTrackerClickDto};
use crate::domain::entity::EngagementLinkTrackerClick;
use crate::infrastructure::persistence::EngagementLinkTrackerClickRepository;

/// Application service for EngagementLinkTrackerClick entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `engagement_link_tracker_click_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EngagementLinkTrackerClickServiceCustom {
///     inner: Arc<EngagementLinkTrackerClickService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EngagementLinkTrackerClickService = GenericCrudService<
    EngagementLinkTrackerClick,
    CreateEngagementLinkTrackerClickDto,
    UpdateEngagementLinkTrackerClickDto,
    EngagementLinkTrackerClickRepository,
>;

// <<< CUSTOM
// END CUSTOM
