//! Application service for EngagementCampaign entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `engagement_campaign_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEngagementCampaignDto, UpdateEngagementCampaignDto};
use crate::domain::entity::EngagementCampaign;
use crate::infrastructure::persistence::EngagementCampaignRepository;

/// Application service for EngagementCampaign entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `engagement_campaign_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EngagementCampaignServiceCustom {
///     inner: Arc<EngagementCampaignService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EngagementCampaignService = GenericCrudService<
    EngagementCampaign,
    CreateEngagementCampaignDto,
    UpdateEngagementCampaignDto,
    EngagementCampaignRepository,
>;

// <<< CUSTOM
// END CUSTOM
