//! Application service for GamificationGoalDefinition entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `gamification_goal_definition_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateGamificationGoalDefinitionDto, UpdateGamificationGoalDefinitionDto};
use crate::domain::entity::GamificationGoalDefinition;
use crate::infrastructure::persistence::GamificationGoalDefinitionRepository;

/// Application service for GamificationGoalDefinition entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `gamification_goal_definition_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct GamificationGoalDefinitionServiceCustom {
///     inner: Arc<GamificationGoalDefinitionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type GamificationGoalDefinitionService = GenericCrudService<
    GamificationGoalDefinition,
    CreateGamificationGoalDefinitionDto,
    UpdateGamificationGoalDefinitionDto,
    GamificationGoalDefinitionRepository,
>;

// <<< CUSTOM
// END CUSTOM
