//! Application service for GamificationGoal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `gamification_goal_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateGamificationGoalDto, UpdateGamificationGoalDto};
use crate::domain::entity::GamificationGoal;
use crate::infrastructure::persistence::GamificationGoalRepository;

/// Application service for GamificationGoal entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `gamification_goal_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct GamificationGoalServiceCustom {
///     inner: Arc<GamificationGoalService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type GamificationGoalService = GenericCrudService<
    GamificationGoal,
    CreateGamificationGoalDto,
    UpdateGamificationGoalDto,
    GamificationGoalRepository,
>;

// <<< CUSTOM
// END CUSTOM
