//! Application service for GamificationChallengeMembership entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `gamification_challenge_membership_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateGamificationChallengeMembershipDto, UpdateGamificationChallengeMembershipDto};
use crate::domain::entity::GamificationChallengeMembership;
use crate::infrastructure::persistence::GamificationChallengeMembershipRepository;

/// Application service for GamificationChallengeMembership entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `gamification_challenge_membership_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct GamificationChallengeMembershipServiceCustom {
///     inner: Arc<GamificationChallengeMembershipService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type GamificationChallengeMembershipService = GenericCrudService<
    GamificationChallengeMembership,
    CreateGamificationChallengeMembershipDto,
    UpdateGamificationChallengeMembershipDto,
    GamificationChallengeMembershipRepository,
>;

// <<< CUSTOM
// END CUSTOM
