//! Application service for GamificationBadge entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `gamification_badge_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateGamificationBadgeDto, UpdateGamificationBadgeDto};
use crate::domain::entity::GamificationBadge;
use crate::infrastructure::persistence::GamificationBadgeRepository;

/// Application service for GamificationBadge entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `gamification_badge_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct GamificationBadgeServiceCustom {
///     inner: Arc<GamificationBadgeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type GamificationBadgeService = GenericCrudService<
    GamificationBadge,
    CreateGamificationBadgeDto,
    UpdateGamificationBadgeDto,
    GamificationBadgeRepository,
>;

// <<< CUSTOM
// END CUSTOM
