//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod engagement_link_tracker_service;
pub mod engagement_link_tracker_click_service;
pub mod engagement_campaign_service;
pub mod engagement_source_service;
pub mod engagement_medium_service;

// <<< CUSTOM
// Hand-authored validated write path (user-owned; see metaphor.codegen.yaml).
pub mod engagement_write_service;
// END CUSTOM

pub use engagement_link_tracker_service::EngagementLinkTrackerService;
pub use engagement_link_tracker_click_service::EngagementLinkTrackerClickService;
pub use engagement_campaign_service::EngagementCampaignService;
pub use engagement_source_service::EngagementSourceService;
pub use engagement_medium_service::EngagementMediumService;
// <<< CUSTOM
pub use engagement_write_service::{
    AttributionInput, AttributionRefs, EngagementError, EngagementWriteService, TrackerView,
};
// END CUSTOM
