-- EngagementLinkTrackerClick Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the engagement.engagement_link_tracker_clicks table.
-- Customize this file to add your initial data.

-- INSERT INTO engagement.engagement_link_tracker_clicks (
--     id,
--     link_id,
--     campaign_id,
--     ip,
--     country_code,
--     click_day,
--     dedup_key,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO engagement.engagement_link_tracker_clicks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

