-- GamificationChallengeLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the engagement.gamification_challenge_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO engagement.gamification_challenge_lines (
--     id,
--     challenge_id,
--     definition_id,
--     sequence,
--     target_goal,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO engagement.gamification_challenge_lines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

