-- GamificationGoal Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the engagement.gamification_goals table.
-- Customize this file to add your initial data.

-- INSERT INTO engagement.gamification_goals (
--     id,
--     definition_id,
--     user_id,
--     line_id,
--     challenge_id,
--     start_date,
--     end_date,
--     target,
--     current,
--     state,
--     to_update,
--     last_update,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO engagement.gamification_goals (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

