-- GamificationChallenge Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the engagement.gamification_challenges table.
-- Customize this file to add your initial data.

-- INSERT INTO engagement.gamification_challenges (
--     id,
--     name,
--     state,
--     manager_user_id,
--     period,
--     start_date,
--     end_date,
--     visibility_mode,
--     reward_badge_id,
--     reward_first_badge_id,
--     reward_second_badge_id,
--     reward_third_badge_id,
--     reward_failure,
--     reward_realtime,
--     report_frequency,
--     last_report_date,
--     next_report_date,
--     remind_update_delay,
--     user_ids,
--     include_all_users,
--     include_badge_ids,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO engagement.gamification_challenges (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

