-- GamificationGoalDefinition Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the engagement.gamification_goal_definitions table.
-- Customize this file to add your initial data.

-- INSERT INTO engagement.gamification_goal_definitions (
--     id,
--     name,
--     description,
--     suffix,
--     monetary,
--     computation_mode,
--     metric_key,
--     condition,
--     display_mode,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO engagement.gamification_goal_definitions (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

