-- GamificationKarmaTracking Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the engagement.gamification_karma_trackings table.
-- Customize this file to add your initial data.

-- INSERT INTO engagement.gamification_karma_trackings (
--     id,
--     user_id,
--     old_value,
--     new_value,
--     tracking_date,
--     reason,
--     origin_kind,
--     origin_id,
--     origin_label,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO engagement.gamification_karma_trackings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

