-- GamificationBadgeUser Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the engagement.gamification_badge_users table.
-- Customize this file to add your initial data.

-- INSERT INTO engagement.gamification_badge_users (
--     id,
--     badge_id,
--     recipient_user_id,
--     sender_user_id,
--     grant_kind,
--     challenge_id,
--     comment,
--     level,
--     granted_at,
--     grant_key,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO engagement.gamification_badge_users (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

