-- Migration: Create gamification_karma_ranks table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS engagement;

CREATE TABLE IF NOT EXISTS engagement.gamification_karma_ranks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    karma_min INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    motivational_text TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_gamification_karma_ranks_karma_min ON engagement.gamification_karma_ranks (karma_min);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_gamification_karma_ranks_metadata_gin ON engagement.gamification_karma_ranks USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_gamification_karma_ranks_metadata_deleted_at ON engagement.gamification_karma_ranks ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_karma_ranks_metadata_created_at ON engagement.gamification_karma_ranks ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_karma_ranks_metadata_updated_at ON engagement.gamification_karma_ranks ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION engagement.gamification_karma_ranks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS gamification_karma_ranks_insert_audit ON engagement.gamification_karma_ranks;
CREATE TRIGGER gamification_karma_ranks_insert_audit BEFORE INSERT ON engagement.gamification_karma_ranks
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_karma_ranks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS gamification_karma_ranks_update_audit ON engagement.gamification_karma_ranks;
CREATE TRIGGER gamification_karma_ranks_update_audit BEFORE UPDATE ON engagement.gamification_karma_ranks
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_karma_ranks_audit_timestamp();
