-- Migration: Create gamification_goal_definitions table
-- Generated by metaphor-schema

-- Create goal_computation_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_computation_mode') THEN
        CREATE TYPE goal_computation_mode AS ENUM ('manual', 'registered_metric');
    END IF;
END
$$;

-- Create goal_condition enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_condition') THEN
        CREATE TYPE goal_condition AS ENUM ('higher', 'lower');
    END IF;
END
$$;

-- Create goal_display_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_display_mode') THEN
        CREATE TYPE goal_display_mode AS ENUM ('progress', 'boolean');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS engagement;

CREATE TABLE IF NOT EXISTS engagement.gamification_goal_definitions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    suffix TEXT,
    monetary BOOLEAN NOT NULL DEFAULT FALSE,
    computation_mode goal_computation_mode NOT NULL DEFAULT 'manual',
    metric_key TEXT,
    condition goal_condition NOT NULL DEFAULT 'higher',
    display_mode goal_display_mode NOT NULL DEFAULT 'progress',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_gamification_goal_definitions_computation_mode_metric_key ON engagement.gamification_goal_definitions (computation_mode, metric_key);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_gamification_goal_definitions_metadata_gin ON engagement.gamification_goal_definitions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_gamification_goal_definitions_metadata_deleted_at ON engagement.gamification_goal_definitions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_goal_definitions_metadata_created_at ON engagement.gamification_goal_definitions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_goal_definitions_metadata_updated_at ON engagement.gamification_goal_definitions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION engagement.gamification_goal_definitions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS gamification_goal_definitions_insert_audit ON engagement.gamification_goal_definitions;
CREATE TRIGGER gamification_goal_definitions_insert_audit BEFORE INSERT ON engagement.gamification_goal_definitions
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_goal_definitions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS gamification_goal_definitions_update_audit ON engagement.gamification_goal_definitions;
CREATE TRIGGER gamification_goal_definitions_update_audit BEFORE UPDATE ON engagement.gamification_goal_definitions
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_goal_definitions_audit_timestamp();
