-- Migration: Create gamification_challenges table
-- Generated by metaphor-schema

-- Create challenge_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'challenge_state') THEN
        CREATE TYPE challenge_state AS ENUM ('draft', 'inprogress', 'done');
    END IF;
END
$$;

-- Create challenge_period enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'challenge_period') THEN
        CREATE TYPE challenge_period AS ENUM ('once', 'daily', 'weekly', 'monthly', 'yearly');
    END IF;
END
$$;

-- Create challenge_visibility_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'challenge_visibility_mode') THEN
        CREATE TYPE challenge_visibility_mode AS ENUM ('personal', 'ranking');
    END IF;
END
$$;

-- Create report_frequency enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'report_frequency') THEN
        CREATE TYPE report_frequency AS ENUM ('never', 'daily', 'weekly', 'monthly', 'yearly');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS engagement;

CREATE TABLE IF NOT EXISTS engagement.gamification_challenges (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    state challenge_state NOT NULL DEFAULT 'draft',
    manager_user_id UUID,
    period challenge_period NOT NULL DEFAULT 'once',
    start_date DATE,
    end_date DATE,
    visibility_mode challenge_visibility_mode NOT NULL DEFAULT 'personal',
    reward_badge_id UUID,
    reward_first_badge_id UUID,
    reward_second_badge_id UUID,
    reward_third_badge_id UUID,
    reward_failure BOOLEAN NOT NULL DEFAULT FALSE,
    reward_realtime BOOLEAN NOT NULL DEFAULT TRUE,
    report_frequency report_frequency NOT NULL DEFAULT 'never',
    last_report_date DATE,
    next_report_date DATE,
    remind_update_delay INTEGER,
    user_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    include_all_users BOOLEAN NOT NULL DEFAULT FALSE,
    include_badge_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_gamification_challenges_state_start_date ON engagement.gamification_challenges (state, start_date);

CREATE INDEX IF NOT EXISTS idx_gamification_challenges_state_end_date ON engagement.gamification_challenges (state, end_date);

CREATE INDEX IF NOT EXISTS idx_gamification_challenges_next_report_date ON engagement.gamification_challenges (next_report_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_gamification_challenges_metadata_gin ON engagement.gamification_challenges USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_gamification_challenges_metadata_deleted_at ON engagement.gamification_challenges ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_challenges_metadata_created_at ON engagement.gamification_challenges ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_challenges_metadata_updated_at ON engagement.gamification_challenges ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION engagement.gamification_challenges_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS gamification_challenges_insert_audit ON engagement.gamification_challenges;
CREATE TRIGGER gamification_challenges_insert_audit BEFORE INSERT ON engagement.gamification_challenges
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_challenges_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS gamification_challenges_update_audit ON engagement.gamification_challenges;
CREATE TRIGGER gamification_challenges_update_audit BEFORE UPDATE ON engagement.gamification_challenges
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_challenges_audit_timestamp();
