-- Migration: Create gamification_challenge_memberships table
-- Generated by metaphor-schema

-- Create membership_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'membership_source') THEN
        CREATE TYPE membership_source AS ENUM ('explicit', 'rule_expansion');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS engagement;

CREATE TABLE IF NOT EXISTS engagement.gamification_challenge_memberships (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    challenge_id UUID NOT NULL,
    user_id UUID NOT NULL,
    source membership_source NOT NULL DEFAULT 'explicit',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_gamification_challenge_memberships_challenge_id_user_id ON engagement.gamification_challenge_memberships (challenge_id, user_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_gamification_challenge_memberships_user_id ON engagement.gamification_challenge_memberships (user_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_gamification_challenge_memberships_metadata_gin ON engagement.gamification_challenge_memberships USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_gamification_challenge_memberships_metadata_deleted_at ON engagement.gamification_challenge_memberships ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_challenge_memberships_metadata_created_at ON engagement.gamification_challenge_memberships ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_gamification_challenge_memberships_metadata_updated_at ON engagement.gamification_challenge_memberships ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION engagement.gamification_challenge_memberships_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS gamification_challenge_memberships_insert_audit ON engagement.gamification_challenge_memberships;
CREATE TRIGGER gamification_challenge_memberships_insert_audit BEFORE INSERT ON engagement.gamification_challenge_memberships
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_challenge_memberships_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS gamification_challenge_memberships_update_audit ON engagement.gamification_challenge_memberships;
CREATE TRIGGER gamification_challenge_memberships_update_audit BEFORE UPDATE ON engagement.gamification_challenge_memberships
    FOR EACH ROW EXECUTE FUNCTION engagement.gamification_challenge_memberships_audit_timestamp();
