-- Enum types for engagement module
-- Generated by metaphor-schema

-- Create badge_level enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'badge_level') THEN
        CREATE TYPE badge_level AS ENUM ('bronze', 'silver', 'gold');
    END IF;
END
$$;

-- Create badge_rule_auth enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'badge_rule_auth') THEN
        CREATE TYPE badge_rule_auth AS ENUM ('everyone', 'users', 'having', 'nobody');
    END IF;
END
$$;

-- Create badge_grant_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'badge_grant_kind') THEN
        CREATE TYPE badge_grant_kind AS ENUM ('peer', 'challenge', 'event');
    END IF;
END
$$;

-- Create challenge_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'challenge_state') THEN
        CREATE TYPE challenge_state AS ENUM ('draft', 'inprogress', 'done');
    END IF;
END
$$;

-- Create challenge_period enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'challenge_period') THEN
        CREATE TYPE challenge_period AS ENUM ('once', 'daily', 'weekly', 'monthly', 'yearly');
    END IF;
END
$$;

-- Create challenge_visibility_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'challenge_visibility_mode') THEN
        CREATE TYPE challenge_visibility_mode AS ENUM ('personal', 'ranking');
    END IF;
END
$$;

-- Create report_frequency enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'report_frequency') THEN
        CREATE TYPE report_frequency AS ENUM ('never', 'daily', 'weekly', 'monthly', 'yearly');
    END IF;
END
$$;

-- Create membership_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'membership_source') THEN
        CREATE TYPE membership_source AS ENUM ('explicit', 'rule_expansion');
    END IF;
END
$$;

-- Create goal_computation_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_computation_mode') THEN
        CREATE TYPE goal_computation_mode AS ENUM ('manual', 'registered_metric');
    END IF;
END
$$;

-- Create goal_condition enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_condition') THEN
        CREATE TYPE goal_condition AS ENUM ('higher', 'lower');
    END IF;
END
$$;

-- Create goal_display_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_display_mode') THEN
        CREATE TYPE goal_display_mode AS ENUM ('progress', 'boolean');
    END IF;
END
$$;

-- Create goal_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_state') THEN
        CREATE TYPE goal_state AS ENUM ('draft', 'inprogress', 'reached', 'failed', 'canceled');
    END IF;
END
$$;

