-- Migration: Create engagement_sources table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS engagement;

CREATE TABLE IF NOT EXISTS engagement.engagement_sources (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_engagement_sources_name ON engagement.engagement_sources (name) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_engagement_sources_metadata_gin ON engagement.engagement_sources USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_engagement_sources_metadata_deleted_at ON engagement.engagement_sources ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_engagement_sources_metadata_created_at ON engagement.engagement_sources ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_engagement_sources_metadata_updated_at ON engagement.engagement_sources ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION engagement.engagement_sources_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS engagement_sources_insert_audit ON engagement.engagement_sources;
CREATE TRIGGER engagement_sources_insert_audit BEFORE INSERT ON engagement.engagement_sources
    FOR EACH ROW EXECUTE FUNCTION engagement.engagement_sources_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS engagement_sources_update_audit ON engagement.engagement_sources;
CREATE TRIGGER engagement_sources_update_audit BEFORE UPDATE ON engagement.engagement_sources
    FOR EACH ROW EXECUTE FUNCTION engagement.engagement_sources_audit_timestamp();
