-- Migration: Create engagement_ratings table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS engagement;

CREATE TABLE IF NOT EXISTS engagement.engagement_ratings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    rated_model TEXT NOT NULL,
    rated_record_id UUID NOT NULL,
    parent_rated_model TEXT,
    parent_rated_record_id UUID,
    rated_user_id UUID,
    rater_user_id UUID,
    rater_email TEXT,
    rating_value INTEGER,
    feedback TEXT,
    consumed BOOLEAN NOT NULL DEFAULT FALSE,
    rated_on TIMESTAMPTZ,
    token_nonce TEXT NOT NULL,
    token_expires_at TIMESTAMPTZ NOT NULL,
    publisher_comment TEXT,
    publisher_user_id UUID,
    publisher_replied_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_engagement_ratings_token_nonce ON engagement.engagement_ratings (token_nonce) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_engagement_ratings_rated_model_rated_record_id_rater_user_id ON engagement.engagement_ratings (rated_model, rated_record_id, rater_user_id) WHERE consumed = false AND rater_user_id IS NOT NULL AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_engagement_ratings_rated_model_rated_record_id ON engagement.engagement_ratings (rated_model, rated_record_id) WHERE consumed = true AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_engagement_ratings_parent_rated_model_parent_rated_record_id ON engagement.engagement_ratings (parent_rated_model, parent_rated_record_id) WHERE consumed = true AND (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_engagement_ratings_metadata_gin ON engagement.engagement_ratings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_engagement_ratings_metadata_deleted_at ON engagement.engagement_ratings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_engagement_ratings_metadata_created_at ON engagement.engagement_ratings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_engagement_ratings_metadata_updated_at ON engagement.engagement_ratings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION engagement.engagement_ratings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS engagement_ratings_insert_audit ON engagement.engagement_ratings;
CREATE TRIGGER engagement_ratings_insert_audit BEFORE INSERT ON engagement.engagement_ratings
    FOR EACH ROW EXECUTE FUNCTION engagement.engagement_ratings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS engagement_ratings_update_audit ON engagement.engagement_ratings;
CREATE TRIGGER engagement_ratings_update_audit BEFORE UPDATE ON engagement.engagement_ratings
    FOR EACH ROW EXECUTE FUNCTION engagement.engagement_ratings_audit_timestamp();
