//! Domain events for EngagementCampaign entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EngagementCampaign;

/// Domain events for EngagementCampaign — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EngagementCampaign>)` variant.
pub type EngagementCampaignEvent = CrudEvent<EngagementCampaign>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EngagementCampaign events.
pub type EngagementCampaignEventPublisher = Arc<dyn CrudEventPublisher<EngagementCampaign> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEngagementCampaignEventPublisher = NoOpCrudEventPublisher<EngagementCampaign>;
