//! Event handler trait for EngagementLinkTracker events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EngagementLinkTrackerEvent;

/// Event handler for EngagementLinkTracker events.
/// Implement this trait to react to EngagementLinkTracker lifecycle events.
pub trait EngagementLinkTrackerEventHandler: EventHandler<EngagementLinkTrackerEvent> {}
