//! Event handler trait for EngagementMedium events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EngagementMediumEvent;

/// Event handler for EngagementMedium events.
/// Implement this trait to react to EngagementMedium lifecycle events.
pub trait EngagementMediumEventHandler: EventHandler<EngagementMediumEvent> {}
