//! Domain events for EngagementSource entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EngagementSource;

/// Domain events for EngagementSource — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EngagementSource>)` variant.
pub type EngagementSourceEvent = CrudEvent<EngagementSource>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EngagementSource events.
pub type EngagementSourceEventPublisher = Arc<dyn CrudEventPublisher<EngagementSource> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEngagementSourceEventPublisher = NoOpCrudEventPublisher<EngagementSource>;
