//! Event handler trait for EngagementRating events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EngagementRatingEvent;

/// Event handler for EngagementRating events.
/// Implement this trait to react to EngagementRating lifecycle events.
pub trait EngagementRatingEventHandler: EventHandler<EngagementRatingEvent> {}
