//! Domain events for EngagementLinkTracker entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EngagementLinkTracker;

/// Domain events for EngagementLinkTracker — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EngagementLinkTracker>)` variant.
pub type EngagementLinkTrackerEvent = CrudEvent<EngagementLinkTracker>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EngagementLinkTracker events.
pub type EngagementLinkTrackerEventPublisher = Arc<dyn CrudEventPublisher<EngagementLinkTracker> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEngagementLinkTrackerEventPublisher = NoOpCrudEventPublisher<EngagementLinkTracker>;
