//! Event handler trait for EngagementLinkTrackerClick events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EngagementLinkTrackerClickEvent;

/// Event handler for EngagementLinkTrackerClick events.
/// Implement this trait to react to EngagementLinkTrackerClick lifecycle events.
pub trait EngagementLinkTrackerClickEventHandler: EventHandler<EngagementLinkTrackerClickEvent> {}
