//! Event handler trait for EngagementSource events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EngagementSourceEvent;

/// Event handler for EngagementSource events.
/// Implement this trait to react to EngagementSource lifecycle events.
pub trait EngagementSourceEventHandler: EventHandler<EngagementSourceEvent> {}
