//! Domain events for GamificationBadgeUser entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GamificationBadgeUser;

/// Domain events for GamificationBadgeUser — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GamificationBadgeUser>)` variant.
pub type GamificationBadgeUserEvent = CrudEvent<GamificationBadgeUser>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GamificationBadgeUser events.
pub type GamificationBadgeUserEventPublisher = Arc<dyn CrudEventPublisher<GamificationBadgeUser> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGamificationBadgeUserEventPublisher = NoOpCrudEventPublisher<GamificationBadgeUser>;
