//! Domain events for GamificationGoal entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GamificationGoal;

/// Domain events for GamificationGoal — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GamificationGoal>)` variant.
pub type GamificationGoalEvent = CrudEvent<GamificationGoal>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GamificationGoal events.
pub type GamificationGoalEventPublisher = Arc<dyn CrudEventPublisher<GamificationGoal> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGamificationGoalEventPublisher = NoOpCrudEventPublisher<GamificationGoal>;
