//! Domain events for GamificationGoalDefinition entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GamificationGoalDefinition;

/// Domain events for GamificationGoalDefinition — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GamificationGoalDefinition>)` variant.
pub type GamificationGoalDefinitionEvent = CrudEvent<GamificationGoalDefinition>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GamificationGoalDefinition events.
pub type GamificationGoalDefinitionEventPublisher = Arc<dyn CrudEventPublisher<GamificationGoalDefinition> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGamificationGoalDefinitionEventPublisher = NoOpCrudEventPublisher<GamificationGoalDefinition>;
