//! Event handler trait for GamificationBadgeUser events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GamificationBadgeUserEvent;

/// Event handler for GamificationBadgeUser events.
/// Implement this trait to react to GamificationBadgeUser lifecycle events.
pub trait GamificationBadgeUserEventHandler: EventHandler<GamificationBadgeUserEvent> {}
