//! Domain events for GamificationBadge entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GamificationBadge;

/// Domain events for GamificationBadge — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GamificationBadge>)` variant.
pub type GamificationBadgeEvent = CrudEvent<GamificationBadge>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GamificationBadge events.
pub type GamificationBadgeEventPublisher = Arc<dyn CrudEventPublisher<GamificationBadge> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGamificationBadgeEventPublisher = NoOpCrudEventPublisher<GamificationBadge>;
