//! Event handler trait for GamificationGoal events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GamificationGoalEvent;

/// Event handler for GamificationGoal events.
/// Implement this trait to react to GamificationGoal lifecycle events.
pub trait GamificationGoalEventHandler: EventHandler<GamificationGoalEvent> {}
