//! Domain events for GamificationKarmaTracking entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GamificationKarmaTracking;

/// Domain events for GamificationKarmaTracking — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GamificationKarmaTracking>)` variant.
pub type GamificationKarmaTrackingEvent = CrudEvent<GamificationKarmaTracking>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GamificationKarmaTracking events.
pub type GamificationKarmaTrackingEventPublisher = Arc<dyn CrudEventPublisher<GamificationKarmaTracking> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGamificationKarmaTrackingEventPublisher = NoOpCrudEventPublisher<GamificationKarmaTracking>;
