//! Event handler trait for GamificationKarmaTracking events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GamificationKarmaTrackingEvent;

/// Event handler for GamificationKarmaTracking events.
/// Implement this trait to react to GamificationKarmaTracking lifecycle events.
pub trait GamificationKarmaTrackingEventHandler: EventHandler<GamificationKarmaTrackingEvent> {}
