//! Event handler trait for GamificationChallengeLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GamificationChallengeLineEvent;

/// Event handler for GamificationChallengeLine events.
/// Implement this trait to react to GamificationChallengeLine lifecycle events.
pub trait GamificationChallengeLineEventHandler: EventHandler<GamificationChallengeLineEvent> {}
