//! Event handler trait for GamificationGoalDefinition events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GamificationGoalDefinitionEvent;

/// Event handler for GamificationGoalDefinition events.
/// Implement this trait to react to GamificationGoalDefinition lifecycle events.
pub trait GamificationGoalDefinitionEventHandler: EventHandler<GamificationGoalDefinitionEvent> {}
