//! Event handler trait for GamificationChallengeMembership events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GamificationChallengeMembershipEvent;

/// Event handler for GamificationChallengeMembership events.
/// Implement this trait to react to GamificationChallengeMembership lifecycle events.
pub trait GamificationChallengeMembershipEventHandler: EventHandler<GamificationChallengeMembershipEvent> {}
