//! Domain events for GamificationChallengeMembership entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GamificationChallengeMembership;

/// Domain events for GamificationChallengeMembership — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GamificationChallengeMembership>)` variant.
pub type GamificationChallengeMembershipEvent = CrudEvent<GamificationChallengeMembership>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GamificationChallengeMembership events.
pub type GamificationChallengeMembershipEventPublisher = Arc<dyn CrudEventPublisher<GamificationChallengeMembership> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGamificationChallengeMembershipEventPublisher = NoOpCrudEventPublisher<GamificationChallengeMembership>;
