//! Domain events for GamificationKarmaRank entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::GamificationKarmaRank;

/// Domain events for GamificationKarmaRank — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<GamificationKarmaRank>)` variant.
pub type GamificationKarmaRankEvent = CrudEvent<GamificationKarmaRank>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for GamificationKarmaRank events.
pub type GamificationKarmaRankEventPublisher = Arc<dyn CrudEventPublisher<GamificationKarmaRank> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGamificationKarmaRankEventPublisher = NoOpCrudEventPublisher<GamificationKarmaRank>;
