//! EngagementLinkTracker seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial EngagementLinkTracker data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ENGAGEMENTLINKTRACKER SEEDER
// ============================================================================

/// Seeder for engagement_link_tracker
pub struct SeedEngagementLinkTrackerSeeder;

impl SeedEngagementLinkTrackerSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEngagementLinkTrackerSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEngagementLinkTrackerSeeder {
    fn name(&self) -> &'static str {
        "SeedEngagementLinkTrackerSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if engagement.engagement_link_trackers table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM engagement.engagement_link_trackers")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/engagement_link_tracker_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM engagement.engagement_link_trackers")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
