//! EngagementSource seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial EngagementSource data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ENGAGEMENTSOURCE SEEDER
// ============================================================================

/// Seeder for engagement_source
pub struct SeedEngagementSourceSeeder;

impl SeedEngagementSourceSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEngagementSourceSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEngagementSourceSeeder {
    fn name(&self) -> &'static str {
        "SeedEngagementSourceSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if engagement.engagement_sources table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM engagement.engagement_sources")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/engagement_source_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM engagement.engagement_sources")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
