//! EngagementMedium seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial EngagementMedium data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ENGAGEMENTMEDIUM SEEDER
// ============================================================================

/// Seeder for engagement_medium
pub struct SeedEngagementMediumSeeder;

impl SeedEngagementMediumSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEngagementMediumSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEngagementMediumSeeder {
    fn name(&self) -> &'static str {
        "SeedEngagementMediumSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if engagement.engagement_media table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM engagement.engagement_media")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/engagement_medium_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM engagement.engagement_media")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
