//! GamificationBadgeUser seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial GamificationBadgeUser data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// GAMIFICATIONBADGEUSER SEEDER
// ============================================================================

/// Seeder for gamification_badge_user
pub struct SeedGamificationBadgeUserSeeder;

impl SeedGamificationBadgeUserSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedGamificationBadgeUserSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedGamificationBadgeUserSeeder {
    fn name(&self) -> &'static str {
        "SeedGamificationBadgeUserSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if engagement.gamification_badge_users table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM engagement.gamification_badge_users")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/gamification_badge_user_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM engagement.gamification_badge_users")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
