//! Repository trait for EngagementCampaign aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EngagementCampaign aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EngagementCampaign;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EngagementCampaignPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EngagementCampaignPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EngagementCampaignPaginatedResult {
    pub data: Vec<EngagementCampaign>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EngagementCampaignFilter {
    pub name: Option<String>,
    pub title: Option<String>,
    pub active: Option<bool>,
    pub user_id: Option<Uuid>,
    pub is_auto_campaign: Option<bool>,
}

impl EngagementCampaignFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.title.is_some() || self.active.is_some() || self.user_id.is_some() || self.is_auto_campaign.is_some()
    }
}

/// Repository trait for EngagementCampaign aggregate
///
/// This trait defines the persistence contract for EngagementCampaign entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EngagementCampaignRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new engagement_campaign entity
    async fn save(&self, entity: &EngagementCampaign) -> Result<EngagementCampaign>;

    /// Find engagement_campaign by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EngagementCampaign>>;

    /// Find all engagement_campaign entities
    async fn find_all(&self) -> Result<Vec<EngagementCampaign>>;

    /// Update engagement_campaign by ID
    async fn update(&self, id: &str, entity: &EngagementCampaign) -> Result<Option<EngagementCampaign>>;

    /// Delete engagement_campaign by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List engagement_campaign with pagination
    async fn list(&self, params: EngagementCampaignPaginationParams) -> Result<EngagementCampaignPaginatedResult>;

    /// List engagement_campaign with pagination and filters
    async fn list_with_filters(&self, params: EngagementCampaignPaginationParams, filters: EngagementCampaignFilter) -> Result<EngagementCampaignPaginatedResult>;

    /// Count all engagement_campaign entities
    async fn count(&self) -> Result<u64>;

    /// Count engagement_campaign entities matching filters
    async fn count_with_filters(&self, filters: EngagementCampaignFilter) -> Result<u64>;

    /// Check if engagement_campaign exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete engagement_campaign by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted engagement_campaign by ID
    async fn restore(&self, id: &str) -> Result<Option<EngagementCampaign>>;

    /// List soft-deleted engagement_campaign entities
    async fn list_deleted(&self, params: EngagementCampaignPaginationParams) -> Result<EngagementCampaignPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save engagement_campaign entities
    async fn bulk_save(&self, entities: &[EngagementCampaign]) -> Result<Vec<EngagementCampaign>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
