//! Repository trait for EngagementRating aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EngagementRating aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EngagementRating;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EngagementRatingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EngagementRatingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EngagementRatingPaginatedResult {
    pub data: Vec<EngagementRating>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EngagementRatingFilter {
    pub rated_model: Option<String>,
    pub rated_record_id: Option<Uuid>,
    pub parent_rated_model: Option<String>,
    pub parent_rated_record_id: Option<Uuid>,
    pub rated_user_id: Option<Uuid>,
    pub rater_user_id: Option<Uuid>,
    pub rater_email: Option<String>,
    pub feedback: Option<String>,
    pub consumed: Option<bool>,
    pub token_nonce: Option<String>,
    pub publisher_comment: Option<String>,
    pub publisher_user_id: Option<Uuid>,
}

impl EngagementRatingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.rated_model.is_some() || self.rated_record_id.is_some() || self.parent_rated_model.is_some() || self.parent_rated_record_id.is_some() || self.rated_user_id.is_some() || self.rater_user_id.is_some() || self.rater_email.is_some() || self.feedback.is_some() || self.consumed.is_some() || self.token_nonce.is_some() || self.publisher_comment.is_some() || self.publisher_user_id.is_some()
    }
}

/// Repository trait for EngagementRating aggregate
///
/// This trait defines the persistence contract for EngagementRating entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EngagementRatingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new engagement_rating entity
    async fn save(&self, entity: &EngagementRating) -> Result<EngagementRating>;

    /// Find engagement_rating by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EngagementRating>>;

    /// Find all engagement_rating entities
    async fn find_all(&self) -> Result<Vec<EngagementRating>>;

    /// Update engagement_rating by ID
    async fn update(&self, id: &str, entity: &EngagementRating) -> Result<Option<EngagementRating>>;

    /// Delete engagement_rating by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List engagement_rating with pagination
    async fn list(&self, params: EngagementRatingPaginationParams) -> Result<EngagementRatingPaginatedResult>;

    /// List engagement_rating with pagination and filters
    async fn list_with_filters(&self, params: EngagementRatingPaginationParams, filters: EngagementRatingFilter) -> Result<EngagementRatingPaginatedResult>;

    /// Count all engagement_rating entities
    async fn count(&self) -> Result<u64>;

    /// Count engagement_rating entities matching filters
    async fn count_with_filters(&self, filters: EngagementRatingFilter) -> Result<u64>;

    /// Check if engagement_rating exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete engagement_rating by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted engagement_rating by ID
    async fn restore(&self, id: &str) -> Result<Option<EngagementRating>>;

    /// List soft-deleted engagement_rating entities
    async fn list_deleted(&self, params: EngagementRatingPaginationParams) -> Result<EngagementRatingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save engagement_rating entities
    async fn bulk_save(&self, entities: &[EngagementRating]) -> Result<Vec<EngagementRating>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
