//! Repository trait for EngagementMedium aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EngagementMedium aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::EngagementMedium;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EngagementMediumPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EngagementMediumPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EngagementMediumPaginatedResult {
    pub data: Vec<EngagementMedium>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EngagementMediumFilter {
    pub name: Option<String>,
    pub active: Option<bool>,
}

impl EngagementMediumFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.active.is_some()
    }
}

/// Repository trait for EngagementMedium aggregate
///
/// This trait defines the persistence contract for EngagementMedium entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EngagementMediumRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new engagement_medium entity
    async fn save(&self, entity: &EngagementMedium) -> Result<EngagementMedium>;

    /// Find engagement_medium by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EngagementMedium>>;

    /// Find all engagement_medium entities
    async fn find_all(&self) -> Result<Vec<EngagementMedium>>;

    /// Update engagement_medium by ID
    async fn update(&self, id: &str, entity: &EngagementMedium) -> Result<Option<EngagementMedium>>;

    /// Delete engagement_medium by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List engagement_medium with pagination
    async fn list(&self, params: EngagementMediumPaginationParams) -> Result<EngagementMediumPaginatedResult>;

    /// List engagement_medium with pagination and filters
    async fn list_with_filters(&self, params: EngagementMediumPaginationParams, filters: EngagementMediumFilter) -> Result<EngagementMediumPaginatedResult>;

    /// Count all engagement_medium entities
    async fn count(&self) -> Result<u64>;

    /// Count engagement_medium entities matching filters
    async fn count_with_filters(&self, filters: EngagementMediumFilter) -> Result<u64>;

    /// Check if engagement_medium exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete engagement_medium by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted engagement_medium by ID
    async fn restore(&self, id: &str) -> Result<Option<EngagementMedium>>;

    /// List soft-deleted engagement_medium entities
    async fn list_deleted(&self, params: EngagementMediumPaginationParams) -> Result<EngagementMediumPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save engagement_medium entities
    async fn bulk_save(&self, entities: &[EngagementMedium]) -> Result<Vec<EngagementMedium>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
