//! Repository trait for GamificationKarmaTracking aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationKarmaTracking aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::GamificationKarmaTracking;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationKarmaTrackingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationKarmaTrackingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationKarmaTrackingPaginatedResult {
    pub data: Vec<GamificationKarmaTracking>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationKarmaTrackingFilter {
    pub user_id: Option<Uuid>,
    pub reason: Option<String>,
    pub origin_kind: Option<String>,
    pub origin_id: Option<Uuid>,
    pub origin_label: Option<String>,
}

impl GamificationKarmaTrackingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.user_id.is_some() || self.reason.is_some() || self.origin_kind.is_some() || self.origin_id.is_some() || self.origin_label.is_some()
    }
}

/// Repository trait for GamificationKarmaTracking aggregate
///
/// This trait defines the persistence contract for GamificationKarmaTracking entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationKarmaTrackingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_karma_tracking entity
    async fn save(&self, entity: &GamificationKarmaTracking) -> Result<GamificationKarmaTracking>;

    /// Find gamification_karma_tracking by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationKarmaTracking>>;

    /// Find all gamification_karma_tracking entities
    async fn find_all(&self) -> Result<Vec<GamificationKarmaTracking>>;

    /// Update gamification_karma_tracking by ID
    async fn update(&self, id: &str, entity: &GamificationKarmaTracking) -> Result<Option<GamificationKarmaTracking>>;

    /// Delete gamification_karma_tracking by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_karma_tracking with pagination
    async fn list(&self, params: GamificationKarmaTrackingPaginationParams) -> Result<GamificationKarmaTrackingPaginatedResult>;

    /// List gamification_karma_tracking with pagination and filters
    async fn list_with_filters(&self, params: GamificationKarmaTrackingPaginationParams, filters: GamificationKarmaTrackingFilter) -> Result<GamificationKarmaTrackingPaginatedResult>;

    /// Count all gamification_karma_tracking entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_karma_tracking entities matching filters
    async fn count_with_filters(&self, filters: GamificationKarmaTrackingFilter) -> Result<u64>;

    /// Check if gamification_karma_tracking exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_karma_tracking by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_karma_tracking by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationKarmaTracking>>;

    /// List soft-deleted gamification_karma_tracking entities
    async fn list_deleted(&self, params: GamificationKarmaTrackingPaginationParams) -> Result<GamificationKarmaTrackingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_karma_tracking entities
    async fn bulk_save(&self, entities: &[GamificationKarmaTracking]) -> Result<Vec<GamificationKarmaTracking>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
