//! Repository trait for GamificationGoal aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationGoal aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{GamificationGoal, GoalState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationGoalPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationGoalPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationGoalPaginatedResult {
    pub data: Vec<GamificationGoal>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationGoalFilter {
    pub definition_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub line_id: Option<Uuid>,
    pub challenge_id: Option<Uuid>,
    pub state: Option<GoalState>,
    pub to_update: Option<bool>,
}

impl GamificationGoalFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.definition_id.is_some() || self.user_id.is_some() || self.line_id.is_some() || self.challenge_id.is_some() || self.state.is_some() || self.to_update.is_some()
    }
}

/// Repository trait for GamificationGoal aggregate
///
/// This trait defines the persistence contract for GamificationGoal entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationGoalRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_goal entity
    async fn save(&self, entity: &GamificationGoal) -> Result<GamificationGoal>;

    /// Find gamification_goal by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationGoal>>;

    /// Find all gamification_goal entities
    async fn find_all(&self) -> Result<Vec<GamificationGoal>>;

    /// Update gamification_goal by ID
    async fn update(&self, id: &str, entity: &GamificationGoal) -> Result<Option<GamificationGoal>>;

    /// Delete gamification_goal by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_goal with pagination
    async fn list(&self, params: GamificationGoalPaginationParams) -> Result<GamificationGoalPaginatedResult>;

    /// List gamification_goal with pagination and filters
    async fn list_with_filters(&self, params: GamificationGoalPaginationParams, filters: GamificationGoalFilter) -> Result<GamificationGoalPaginatedResult>;

    /// Count all gamification_goal entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_goal entities matching filters
    async fn count_with_filters(&self, filters: GamificationGoalFilter) -> Result<u64>;

    /// Check if gamification_goal exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_goal by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_goal by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationGoal>>;

    /// List soft-deleted gamification_goal entities
    async fn list_deleted(&self, params: GamificationGoalPaginationParams) -> Result<GamificationGoalPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_goal entities
    async fn bulk_save(&self, entities: &[GamificationGoal]) -> Result<Vec<GamificationGoal>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
