//! Repository trait for GamificationBadge aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationBadge aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{GamificationBadge, BadgeLevel, BadgeRuleAuth};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationBadgePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationBadgePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationBadgePaginatedResult {
    pub data: Vec<GamificationBadge>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationBadgeFilter {
    pub name: Option<String>,
    pub active: Option<bool>,
    pub level: Option<BadgeLevel>,
    pub description: Option<String>,
    pub rule_auth: Option<BadgeRuleAuth>,
    pub rule_max: Option<bool>,
}

impl GamificationBadgeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.active.is_some() || self.level.is_some() || self.description.is_some() || self.rule_auth.is_some() || self.rule_max.is_some()
    }
}

/// Repository trait for GamificationBadge aggregate
///
/// This trait defines the persistence contract for GamificationBadge entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationBadgeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_badge entity
    async fn save(&self, entity: &GamificationBadge) -> Result<GamificationBadge>;

    /// Find gamification_badge by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationBadge>>;

    /// Find all gamification_badge entities
    async fn find_all(&self) -> Result<Vec<GamificationBadge>>;

    /// Update gamification_badge by ID
    async fn update(&self, id: &str, entity: &GamificationBadge) -> Result<Option<GamificationBadge>>;

    /// Delete gamification_badge by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_badge with pagination
    async fn list(&self, params: GamificationBadgePaginationParams) -> Result<GamificationBadgePaginatedResult>;

    /// List gamification_badge with pagination and filters
    async fn list_with_filters(&self, params: GamificationBadgePaginationParams, filters: GamificationBadgeFilter) -> Result<GamificationBadgePaginatedResult>;

    /// Count all gamification_badge entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_badge entities matching filters
    async fn count_with_filters(&self, filters: GamificationBadgeFilter) -> Result<u64>;

    /// Check if gamification_badge exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_badge by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_badge by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationBadge>>;

    /// List soft-deleted gamification_badge entities
    async fn list_deleted(&self, params: GamificationBadgePaginationParams) -> Result<GamificationBadgePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_badge entities
    async fn bulk_save(&self, entities: &[GamificationBadge]) -> Result<Vec<GamificationBadge>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
