//! Repository trait for GamificationBadgeUser aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationBadgeUser aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{GamificationBadgeUser, BadgeGrantKind, BadgeLevel};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationBadgeUserPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationBadgeUserPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationBadgeUserPaginatedResult {
    pub data: Vec<GamificationBadgeUser>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationBadgeUserFilter {
    pub badge_id: Option<Uuid>,
    pub recipient_user_id: Option<Uuid>,
    pub sender_user_id: Option<Uuid>,
    pub grant_kind: Option<BadgeGrantKind>,
    pub challenge_id: Option<Uuid>,
    pub comment: Option<String>,
    pub level: Option<BadgeLevel>,
    pub grant_key: Option<String>,
}

impl GamificationBadgeUserFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.badge_id.is_some() || self.recipient_user_id.is_some() || self.sender_user_id.is_some() || self.grant_kind.is_some() || self.challenge_id.is_some() || self.comment.is_some() || self.level.is_some() || self.grant_key.is_some()
    }
}

/// Repository trait for GamificationBadgeUser aggregate
///
/// This trait defines the persistence contract for GamificationBadgeUser entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationBadgeUserRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_badge_user entity
    async fn save(&self, entity: &GamificationBadgeUser) -> Result<GamificationBadgeUser>;

    /// Find gamification_badge_user by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationBadgeUser>>;

    /// Find all gamification_badge_user entities
    async fn find_all(&self) -> Result<Vec<GamificationBadgeUser>>;

    /// Update gamification_badge_user by ID
    async fn update(&self, id: &str, entity: &GamificationBadgeUser) -> Result<Option<GamificationBadgeUser>>;

    /// Delete gamification_badge_user by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_badge_user with pagination
    async fn list(&self, params: GamificationBadgeUserPaginationParams) -> Result<GamificationBadgeUserPaginatedResult>;

    /// List gamification_badge_user with pagination and filters
    async fn list_with_filters(&self, params: GamificationBadgeUserPaginationParams, filters: GamificationBadgeUserFilter) -> Result<GamificationBadgeUserPaginatedResult>;

    /// Count all gamification_badge_user entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_badge_user entities matching filters
    async fn count_with_filters(&self, filters: GamificationBadgeUserFilter) -> Result<u64>;

    /// Check if gamification_badge_user exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_badge_user by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_badge_user by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationBadgeUser>>;

    /// List soft-deleted gamification_badge_user entities
    async fn list_deleted(&self, params: GamificationBadgeUserPaginationParams) -> Result<GamificationBadgeUserPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_badge_user entities
    async fn bulk_save(&self, entities: &[GamificationBadgeUser]) -> Result<Vec<GamificationBadgeUser>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
