//! Repository trait for GamificationChallengeMembership aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationChallengeMembership aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{GamificationChallengeMembership, MembershipSource};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationChallengeMembershipPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationChallengeMembershipPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationChallengeMembershipPaginatedResult {
    pub data: Vec<GamificationChallengeMembership>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationChallengeMembershipFilter {
    pub challenge_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub source: Option<MembershipSource>,
}

impl GamificationChallengeMembershipFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.challenge_id.is_some() || self.user_id.is_some() || self.source.is_some()
    }
}

/// Repository trait for GamificationChallengeMembership aggregate
///
/// This trait defines the persistence contract for GamificationChallengeMembership entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationChallengeMembershipRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_challenge_membership entity
    async fn save(&self, entity: &GamificationChallengeMembership) -> Result<GamificationChallengeMembership>;

    /// Find gamification_challenge_membership by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationChallengeMembership>>;

    /// Find all gamification_challenge_membership entities
    async fn find_all(&self) -> Result<Vec<GamificationChallengeMembership>>;

    /// Update gamification_challenge_membership by ID
    async fn update(&self, id: &str, entity: &GamificationChallengeMembership) -> Result<Option<GamificationChallengeMembership>>;

    /// Delete gamification_challenge_membership by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_challenge_membership with pagination
    async fn list(&self, params: GamificationChallengeMembershipPaginationParams) -> Result<GamificationChallengeMembershipPaginatedResult>;

    /// List gamification_challenge_membership with pagination and filters
    async fn list_with_filters(&self, params: GamificationChallengeMembershipPaginationParams, filters: GamificationChallengeMembershipFilter) -> Result<GamificationChallengeMembershipPaginatedResult>;

    /// Count all gamification_challenge_membership entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_challenge_membership entities matching filters
    async fn count_with_filters(&self, filters: GamificationChallengeMembershipFilter) -> Result<u64>;

    /// Check if gamification_challenge_membership exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_challenge_membership by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_challenge_membership by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationChallengeMembership>>;

    /// List soft-deleted gamification_challenge_membership entities
    async fn list_deleted(&self, params: GamificationChallengeMembershipPaginationParams) -> Result<GamificationChallengeMembershipPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_challenge_membership entities
    async fn bulk_save(&self, entities: &[GamificationChallengeMembership]) -> Result<Vec<GamificationChallengeMembership>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
