//! Repository trait for GamificationKarmaRank aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationKarmaRank aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::GamificationKarmaRank;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationKarmaRankPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationKarmaRankPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationKarmaRankPaginatedResult {
    pub data: Vec<GamificationKarmaRank>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationKarmaRankFilter {
    pub name: Option<String>,
    pub description: Option<String>,
    pub motivational_text: Option<String>,
}

impl GamificationKarmaRankFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.description.is_some() || self.motivational_text.is_some()
    }
}

/// Repository trait for GamificationKarmaRank aggregate
///
/// This trait defines the persistence contract for GamificationKarmaRank entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationKarmaRankRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_karma_rank entity
    async fn save(&self, entity: &GamificationKarmaRank) -> Result<GamificationKarmaRank>;

    /// Find gamification_karma_rank by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationKarmaRank>>;

    /// Find all gamification_karma_rank entities
    async fn find_all(&self) -> Result<Vec<GamificationKarmaRank>>;

    /// Update gamification_karma_rank by ID
    async fn update(&self, id: &str, entity: &GamificationKarmaRank) -> Result<Option<GamificationKarmaRank>>;

    /// Delete gamification_karma_rank by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_karma_rank with pagination
    async fn list(&self, params: GamificationKarmaRankPaginationParams) -> Result<GamificationKarmaRankPaginatedResult>;

    /// List gamification_karma_rank with pagination and filters
    async fn list_with_filters(&self, params: GamificationKarmaRankPaginationParams, filters: GamificationKarmaRankFilter) -> Result<GamificationKarmaRankPaginatedResult>;

    /// Count all gamification_karma_rank entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_karma_rank entities matching filters
    async fn count_with_filters(&self, filters: GamificationKarmaRankFilter) -> Result<u64>;

    /// Check if gamification_karma_rank exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_karma_rank by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_karma_rank by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationKarmaRank>>;

    /// List soft-deleted gamification_karma_rank entities
    async fn list_deleted(&self, params: GamificationKarmaRankPaginationParams) -> Result<GamificationKarmaRankPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_karma_rank entities
    async fn bulk_save(&self, entities: &[GamificationKarmaRank]) -> Result<Vec<GamificationKarmaRank>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
