//! Repository trait for GamificationChallenge aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationChallenge aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{GamificationChallenge, ChallengePeriod, ChallengeState, ChallengeVisibilityMode, ReportFrequency};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationChallengePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationChallengePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationChallengePaginatedResult {
    pub data: Vec<GamificationChallenge>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationChallengeFilter {
    pub name: Option<String>,
    pub state: Option<ChallengeState>,
    pub manager_user_id: Option<Uuid>,
    pub period: Option<ChallengePeriod>,
    pub visibility_mode: Option<ChallengeVisibilityMode>,
    pub reward_badge_id: Option<Uuid>,
    pub reward_first_badge_id: Option<Uuid>,
    pub reward_second_badge_id: Option<Uuid>,
    pub reward_third_badge_id: Option<Uuid>,
    pub reward_failure: Option<bool>,
    pub reward_realtime: Option<bool>,
    pub report_frequency: Option<ReportFrequency>,
    pub include_all_users: Option<bool>,
}

impl GamificationChallengeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.state.is_some() || self.manager_user_id.is_some() || self.period.is_some() || self.visibility_mode.is_some() || self.reward_badge_id.is_some() || self.reward_first_badge_id.is_some() || self.reward_second_badge_id.is_some() || self.reward_third_badge_id.is_some() || self.reward_failure.is_some() || self.reward_realtime.is_some() || self.report_frequency.is_some() || self.include_all_users.is_some()
    }
}

/// Repository trait for GamificationChallenge aggregate
///
/// This trait defines the persistence contract for GamificationChallenge entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationChallengeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_challenge entity
    async fn save(&self, entity: &GamificationChallenge) -> Result<GamificationChallenge>;

    /// Find gamification_challenge by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationChallenge>>;

    /// Find all gamification_challenge entities
    async fn find_all(&self) -> Result<Vec<GamificationChallenge>>;

    /// Update gamification_challenge by ID
    async fn update(&self, id: &str, entity: &GamificationChallenge) -> Result<Option<GamificationChallenge>>;

    /// Delete gamification_challenge by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_challenge with pagination
    async fn list(&self, params: GamificationChallengePaginationParams) -> Result<GamificationChallengePaginatedResult>;

    /// List gamification_challenge with pagination and filters
    async fn list_with_filters(&self, params: GamificationChallengePaginationParams, filters: GamificationChallengeFilter) -> Result<GamificationChallengePaginatedResult>;

    /// Count all gamification_challenge entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_challenge entities matching filters
    async fn count_with_filters(&self, filters: GamificationChallengeFilter) -> Result<u64>;

    /// Check if gamification_challenge exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_challenge by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_challenge by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationChallenge>>;

    /// List soft-deleted gamification_challenge entities
    async fn list_deleted(&self, params: GamificationChallengePaginationParams) -> Result<GamificationChallengePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_challenge entities
    async fn bulk_save(&self, entities: &[GamificationChallenge]) -> Result<Vec<GamificationChallenge>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
