//! Repository trait for GamificationGoalDefinition aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the GamificationGoalDefinition aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{GamificationGoalDefinition, GoalComputationMode, GoalCondition, GoalDisplayMode};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationGoalDefinitionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl GamificationGoalDefinitionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct GamificationGoalDefinitionPaginatedResult {
    pub data: Vec<GamificationGoalDefinition>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct GamificationGoalDefinitionFilter {
    pub name: Option<String>,
    pub description: Option<String>,
    pub suffix: Option<String>,
    pub monetary: Option<bool>,
    pub computation_mode: Option<GoalComputationMode>,
    pub metric_key: Option<String>,
    pub condition: Option<GoalCondition>,
    pub display_mode: Option<GoalDisplayMode>,
}

impl GamificationGoalDefinitionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.description.is_some() || self.suffix.is_some() || self.monetary.is_some() || self.computation_mode.is_some() || self.metric_key.is_some() || self.condition.is_some() || self.display_mode.is_some()
    }
}

/// Repository trait for GamificationGoalDefinition aggregate
///
/// This trait defines the persistence contract for GamificationGoalDefinition entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait GamificationGoalDefinitionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new gamification_goal_definition entity
    async fn save(&self, entity: &GamificationGoalDefinition) -> Result<GamificationGoalDefinition>;

    /// Find gamification_goal_definition by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<GamificationGoalDefinition>>;

    /// Find all gamification_goal_definition entities
    async fn find_all(&self) -> Result<Vec<GamificationGoalDefinition>>;

    /// Update gamification_goal_definition by ID
    async fn update(&self, id: &str, entity: &GamificationGoalDefinition) -> Result<Option<GamificationGoalDefinition>>;

    /// Delete gamification_goal_definition by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List gamification_goal_definition with pagination
    async fn list(&self, params: GamificationGoalDefinitionPaginationParams) -> Result<GamificationGoalDefinitionPaginatedResult>;

    /// List gamification_goal_definition with pagination and filters
    async fn list_with_filters(&self, params: GamificationGoalDefinitionPaginationParams, filters: GamificationGoalDefinitionFilter) -> Result<GamificationGoalDefinitionPaginatedResult>;

    /// Count all gamification_goal_definition entities
    async fn count(&self) -> Result<u64>;

    /// Count gamification_goal_definition entities matching filters
    async fn count_with_filters(&self, filters: GamificationGoalDefinitionFilter) -> Result<u64>;

    /// Check if gamification_goal_definition exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete gamification_goal_definition by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted gamification_goal_definition by ID
    async fn restore(&self, id: &str) -> Result<Option<GamificationGoalDefinition>>;

    /// List soft-deleted gamification_goal_definition entities
    async fn list_deleted(&self, params: GamificationGoalDefinitionPaginationParams) -> Result<GamificationGoalDefinitionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save gamification_goal_definition entities
    async fn bulk_save(&self, entities: &[GamificationGoalDefinition]) -> Result<Vec<GamificationGoalDefinition>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
