//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod engagement_link_tracker_repository;
pub mod engagement_link_tracker_click_repository;
pub mod engagement_campaign_repository;
pub mod engagement_source_repository;
pub mod engagement_medium_repository;

// Re-exports
pub use engagement_link_tracker_repository::{
    EngagementLinkTrackerRepository,
    EngagementLinkTrackerPaginationParams,
    EngagementLinkTrackerPaginatedResult,
    EngagementLinkTrackerFilter,
};
pub use engagement_link_tracker_click_repository::{
    EngagementLinkTrackerClickRepository,
    EngagementLinkTrackerClickPaginationParams,
    EngagementLinkTrackerClickPaginatedResult,
    EngagementLinkTrackerClickFilter,
};
pub use engagement_campaign_repository::{
    EngagementCampaignRepository,
    EngagementCampaignPaginationParams,
    EngagementCampaignPaginatedResult,
    EngagementCampaignFilter,
};
pub use engagement_source_repository::{
    EngagementSourceRepository,
    EngagementSourcePaginationParams,
    EngagementSourcePaginatedResult,
    EngagementSourceFilter,
};
pub use engagement_medium_repository::{
    EngagementMediumRepository,
    EngagementMediumPaginationParams,
    EngagementMediumPaginatedResult,
    EngagementMediumFilter,
};
