//! Repository for EngagementLinkTracker entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EngagementLinkTracker, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EngagementLinkTracker;

/// Table name for EngagementLinkTracker entities
pub const TABLE_NAME: &str = "engagement.engagement_link_trackers";

/// Repository for EngagementLinkTracker entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EngagementLinkTrackerRepository(
    backbone_orm::GenericCrudRepository<EngagementLinkTracker, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EngagementLinkTrackerRepository {
    type Target = backbone_orm::GenericCrudRepository<EngagementLinkTracker, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EngagementLinkTrackerRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EngagementLinkTrackerRepository, EngagementLinkTracker, soft_delete);
