//! Repository for EngagementRating entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EngagementRating, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EngagementRating;

/// Table name for EngagementRating entities
pub const TABLE_NAME: &str = "engagement.engagement_ratings";

/// Repository for EngagementRating entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EngagementRatingRepository(
    backbone_orm::GenericCrudRepository<EngagementRating, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EngagementRatingRepository {
    type Target = backbone_orm::GenericCrudRepository<EngagementRating, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EngagementRatingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EngagementRatingRepository, EngagementRating, soft_delete);
