//! Repository for GamificationChallenge entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<GamificationChallenge, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::GamificationChallenge;

/// Table name for GamificationChallenge entities
pub const TABLE_NAME: &str = "engagement.gamification_challenges";

/// Repository for GamificationChallenge entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct GamificationChallengeRepository(
    backbone_orm::GenericCrudRepository<GamificationChallenge, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for GamificationChallengeRepository {
    type Target = backbone_orm::GenericCrudRepository<GamificationChallenge, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl GamificationChallengeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(GamificationChallengeRepository, GamificationChallenge, soft_delete);
