//! Repository for GamificationBadge entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<GamificationBadge, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::GamificationBadge;

/// Table name for GamificationBadge entities
pub const TABLE_NAME: &str = "engagement.gamification_badges";

/// Repository for GamificationBadge entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct GamificationBadgeRepository(
    backbone_orm::GenericCrudRepository<GamificationBadge, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for GamificationBadgeRepository {
    type Target = backbone_orm::GenericCrudRepository<GamificationBadge, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl GamificationBadgeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(GamificationBadgeRepository, GamificationBadge, soft_delete);
