//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod engagement_link_tracker_repository;
mod engagement_link_tracker_click_repository;
mod engagement_campaign_repository;
mod engagement_source_repository;
mod engagement_medium_repository;

// Custom persistence modules
// <<< CUSTOM
// Hand-written engagement SQL (services orchestrate, repositories hold SQL).
pub mod engagement_repository;
// END CUSTOM

// Re-exports
pub use engagement_link_tracker_repository::EngagementLinkTrackerRepository;
pub use engagement_link_tracker_click_repository::EngagementLinkTrackerClickRepository;
pub use engagement_campaign_repository::EngagementCampaignRepository;
pub use engagement_source_repository::EngagementSourceRepository;
pub use engagement_medium_repository::EngagementMediumRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use engagement_repository::EngagementRepository;
// END CUSTOM
