//! Validator for EngagementLinkTrackerClick entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EngagementLinkTrackerClick>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::EngagementLinkTrackerClick;

/// Validator type alias for EngagementLinkTrackerClick entities.
pub type EngagementLinkTrackerClickValidator = EntityValidator<EngagementLinkTrackerClick>;

/// Build a validator for EngagementLinkTrackerClick with all schema-defined field rules.
pub fn engagement_link_tracker_click_validator() -> EngagementLinkTrackerClickValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("ip", |e: &EngagementLinkTrackerClick| e.ip.as_deref()))
        .rule(OptionalNotBlank::new("country_code", |e: &EngagementLinkTrackerClick| e.country_code.as_deref()))
        .rule(RequiredString::new("dedup_key", |e: &EngagementLinkTrackerClick| &e.dedup_key))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
