//! Validator for EngagementLinkTracker entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EngagementLinkTracker>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::EngagementLinkTracker;

/// Validator type alias for EngagementLinkTracker entities.
pub type EngagementLinkTrackerValidator = EntityValidator<EngagementLinkTracker>;

/// Build a validator for EngagementLinkTracker with all schema-defined field rules.
pub fn engagement_link_tracker_validator() -> EngagementLinkTrackerValidator {
    EntityValidator::new()
        .rule(RequiredString::new("url", |e: &EngagementLinkTracker| &e.url))
        .rule(RequiredString::new("code", |e: &EngagementLinkTracker| &e.code))
        .rule(OptionalNotBlank::new("title", |e: &EngagementLinkTracker| e.title.as_deref()))
        .rule(RequiredString::new("label", |e: &EngagementLinkTracker| &e.label))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
