//! Validator for EngagementCampaign entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EngagementCampaign>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::EngagementCampaign;

/// Validator type alias for EngagementCampaign entities.
pub type EngagementCampaignValidator = EntityValidator<EngagementCampaign>;

/// Build a validator for EngagementCampaign with all schema-defined field rules.
pub fn engagement_campaign_validator() -> EngagementCampaignValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &EngagementCampaign| &e.name))
        .rule(RequiredString::new("title", |e: &EngagementCampaign| &e.title))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
