//! Validator for EngagementSource entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EngagementSource>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::EngagementSource;

/// Validator type alias for EngagementSource entities.
pub type EngagementSourceValidator = EntityValidator<EngagementSource>;

/// Build a validator for EngagementSource with all schema-defined field rules.
pub fn engagement_source_validator() -> EngagementSourceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &EngagementSource| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
