//! Validator for EngagementMedium entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EngagementMedium>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::EngagementMedium;

/// Validator type alias for EngagementMedium entities.
pub type EngagementMediumValidator = EntityValidator<EngagementMedium>;

/// Build a validator for EngagementMedium with all schema-defined field rules.
pub fn engagement_medium_validator() -> EngagementMediumValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &EngagementMedium| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
