//! Validator for GamificationKarmaRank entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GamificationKarmaRank>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::GamificationKarmaRank;

/// Validator type alias for GamificationKarmaRank entities.
pub type GamificationKarmaRankValidator = EntityValidator<GamificationKarmaRank>;

/// Build a validator for GamificationKarmaRank with all schema-defined field rules.
pub fn gamification_karma_rank_validator() -> GamificationKarmaRankValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &GamificationKarmaRank| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &GamificationKarmaRank| e.description.as_deref()))
        .rule(OptionalNotBlank::new("motivational_text", |e: &GamificationKarmaRank| e.motivational_text.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
