//! Validator for GamificationBadge entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GamificationBadge>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::GamificationBadge;

/// Validator type alias for GamificationBadge entities.
pub type GamificationBadgeValidator = EntityValidator<GamificationBadge>;

/// Build a validator for GamificationBadge with all schema-defined field rules.
pub fn gamification_badge_validator() -> GamificationBadgeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &GamificationBadge| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &GamificationBadge| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
