//! Validator for GamificationChallengeMembership entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GamificationChallengeMembership>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::GamificationChallengeMembership;

/// Validator type alias for GamificationChallengeMembership entities.
pub type GamificationChallengeMembershipValidator = EntityValidator<GamificationChallengeMembership>;

/// Build a validator for GamificationChallengeMembership with all schema-defined field rules.
pub fn gamification_challenge_membership_validator() -> GamificationChallengeMembershipValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
