//! Validator for GamificationBadgeUser entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GamificationBadgeUser>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::GamificationBadgeUser;

/// Validator type alias for GamificationBadgeUser entities.
pub type GamificationBadgeUserValidator = EntityValidator<GamificationBadgeUser>;

/// Build a validator for GamificationBadgeUser with all schema-defined field rules.
pub fn gamification_badge_user_validator() -> GamificationBadgeUserValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("comment", |e: &GamificationBadgeUser| e.comment.as_deref()))
        .rule(OptionalNotBlank::new("grant_key", |e: &GamificationBadgeUser| e.grant_key.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
