//! Validator for GamificationKarmaTracking entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GamificationKarmaTracking>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::GamificationKarmaTracking;

/// Validator type alias for GamificationKarmaTracking entities.
pub type GamificationKarmaTrackingValidator = EntityValidator<GamificationKarmaTracking>;

/// Build a validator for GamificationKarmaTracking with all schema-defined field rules.
pub fn gamification_karma_tracking_validator() -> GamificationKarmaTrackingValidator {
    EntityValidator::new()
        .rule(RequiredString::new("reason", |e: &GamificationKarmaTracking| &e.reason))
        .rule(RequiredString::new("origin_kind", |e: &GamificationKarmaTracking| &e.origin_kind))
        .rule(OptionalNotBlank::new("origin_label", |e: &GamificationKarmaTracking| e.origin_label.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
