//! Validator for GamificationGoalDefinition entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GamificationGoalDefinition>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::GamificationGoalDefinition;

/// Validator type alias for GamificationGoalDefinition entities.
pub type GamificationGoalDefinitionValidator = EntityValidator<GamificationGoalDefinition>;

/// Build a validator for GamificationGoalDefinition with all schema-defined field rules.
pub fn gamification_goal_definition_validator() -> GamificationGoalDefinitionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &GamificationGoalDefinition| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &GamificationGoalDefinition| e.description.as_deref()))
        .rule(OptionalNotBlank::new("suffix", |e: &GamificationGoalDefinition| e.suffix.as_deref()))
        .rule(OptionalNotBlank::new("metric_key", |e: &GamificationGoalDefinition| e.metric_key.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
