//! Validator for GamificationChallenge entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<GamificationChallenge>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::GamificationChallenge;

/// Validator type alias for GamificationChallenge entities.
pub type GamificationChallengeValidator = EntityValidator<GamificationChallenge>;

/// Build a validator for GamificationChallenge with all schema-defined field rules.
pub fn gamification_challenge_validator() -> GamificationChallengeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &GamificationChallenge| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
