//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod gamification_badge;
pub mod gamification_badge_user;
pub mod gamification_karma_tracking;
pub mod gamification_karma_rank;
pub mod gamification_challenge;
pub mod gamification_challenge_membership;
pub mod gamification_challenge_line;
pub mod gamification_goal_definition;
pub mod gamification_goal;
pub mod engagement_link_tracker;
pub mod engagement_link_tracker_click;
pub mod engagement_rating;
pub mod engagement_campaign;
pub mod engagement_source;
pub mod engagement_medium;
pub mod badge_level;
pub mod badge_rule_auth;
pub mod badge_grant_kind;
pub mod challenge_state;
pub mod challenge_period;
pub mod challenge_visibility_mode;
pub mod report_frequency;
pub mod membership_source;
pub mod goal_computation_mode;
pub mod goal_condition;
pub mod goal_display_mode;
pub mod goal_state;

// Re-exports
pub use gamification_badge::GamificationBadge;
pub use gamification_badge::GamificationBadgeBuilder;
pub use gamification_badge::GamificationBadgeId;
pub use gamification_badge_user::GamificationBadgeUser;
pub use gamification_badge_user::GamificationBadgeUserBuilder;
pub use gamification_badge_user::GamificationBadgeUserId;
pub use gamification_karma_tracking::GamificationKarmaTracking;
pub use gamification_karma_tracking::GamificationKarmaTrackingBuilder;
pub use gamification_karma_tracking::GamificationKarmaTrackingId;
pub use gamification_karma_rank::GamificationKarmaRank;
pub use gamification_karma_rank::GamificationKarmaRankBuilder;
pub use gamification_karma_rank::GamificationKarmaRankId;
pub use gamification_challenge::GamificationChallenge;
pub use gamification_challenge::GamificationChallengeBuilder;
pub use gamification_challenge::GamificationChallengeId;
pub use gamification_challenge_membership::GamificationChallengeMembership;
pub use gamification_challenge_membership::GamificationChallengeMembershipBuilder;
pub use gamification_challenge_membership::GamificationChallengeMembershipId;
pub use gamification_challenge_line::GamificationChallengeLine;
pub use gamification_challenge_line::GamificationChallengeLineBuilder;
pub use gamification_challenge_line::GamificationChallengeLineId;
pub use gamification_goal_definition::GamificationGoalDefinition;
pub use gamification_goal_definition::GamificationGoalDefinitionBuilder;
pub use gamification_goal_definition::GamificationGoalDefinitionId;
pub use gamification_goal::GamificationGoal;
pub use gamification_goal::GamificationGoalBuilder;
pub use gamification_goal::GamificationGoalId;
pub use engagement_link_tracker::EngagementLinkTracker;
pub use engagement_link_tracker::EngagementLinkTrackerBuilder;
pub use engagement_link_tracker::EngagementLinkTrackerId;
pub use engagement_link_tracker_click::EngagementLinkTrackerClick;
pub use engagement_link_tracker_click::EngagementLinkTrackerClickBuilder;
pub use engagement_link_tracker_click::EngagementLinkTrackerClickId;
pub use engagement_rating::EngagementRating;
pub use engagement_rating::EngagementRatingBuilder;
pub use engagement_rating::EngagementRatingId;
pub use engagement_campaign::EngagementCampaign;
pub use engagement_campaign::EngagementCampaignBuilder;
pub use engagement_campaign::EngagementCampaignId;
pub use engagement_source::EngagementSource;
pub use engagement_source::EngagementSourceBuilder;
pub use engagement_source::EngagementSourceId;
pub use engagement_medium::EngagementMedium;
pub use engagement_medium::EngagementMediumBuilder;
pub use engagement_medium::EngagementMediumId;
pub use badge_level::BadgeLevel;
pub use badge_rule_auth::BadgeRuleAuth;
pub use badge_grant_kind::BadgeGrantKind;
pub use challenge_state::ChallengeState;
pub use challenge_period::ChallengePeriod;
pub use challenge_visibility_mode::ChallengeVisibilityMode;
pub use report_frequency::ReportFrequency;
pub use membership_source::MembershipSource;
pub use goal_computation_mode::GoalComputationMode;
pub use goal_condition::GoalCondition;
pub use goal_display_mode::GoalDisplayMode;
pub use goal_state::GoalState;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
