//! EngagementLinkTrackerClick API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EngagementLinkTrackerClick CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ENGAGEMENTLINKTRACKERCLICK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EngagementLinkTrackerClick
pub struct EngagementLinkTrackerClickTestData;

impl TestDataGenerator for EngagementLinkTrackerClickTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "link_id": Uuid::new_v4().to_string(),
            "campaign_id": null,
            "ip": null,
            "country_code": null,
            "click_day": Utc::now().format("%Y-%m-%d").to_string(),
            "dedup_key": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "link_id": Uuid::new_v4().to_string(),
            "campaign_id": null,
            "ip": null,
            "country_code": null,
            "click_day": Utc::now().format("%Y-%m-%d").to_string(),
            "dedup_key": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ENGAGEMENTLINKTRACKERCLICK API TEST
// ============================================================================

/// EngagementLinkTrackerClick API test suite
pub struct EngagementLinkTrackerClickApiTest {
    inner: GenericCrudTest<EngagementLinkTrackerClickTestData>,
}

impl EngagementLinkTrackerClickApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/engagement_link_tracker_clicks", "EngagementLinkTrackerClick");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EngagementLinkTrackerClickTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EngagementLinkTrackerClickApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_engagement_link_tracker_click_crud() {
        let mut test = EngagementLinkTrackerClickApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EngagementLinkTrackerClick specific tests here
// <<< CUSTOM TESTS END >>>
