//! EngagementCampaign API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EngagementCampaign CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ENGAGEMENTCAMPAIGN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EngagementCampaign
pub struct EngagementCampaignTestData;

impl TestDataGenerator for EngagementCampaignTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "active": false,
            "user_id": null,
            "is_auto_campaign": false,
            "color": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "active": false,
            "user_id": null,
            "is_auto_campaign": false,
            "color": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ENGAGEMENTCAMPAIGN API TEST
// ============================================================================

/// EngagementCampaign API test suite
pub struct EngagementCampaignApiTest {
    inner: GenericCrudTest<EngagementCampaignTestData>,
}

impl EngagementCampaignApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/engagement_campaigns", "EngagementCampaign");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EngagementCampaignTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EngagementCampaignApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_engagement_campaign_crud() {
        let mut test = EngagementCampaignApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EngagementCampaign specific tests here
// <<< CUSTOM TESTS END >>>
