//! EngagementSource API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EngagementSource CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ENGAGEMENTSOURCE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EngagementSource
pub struct EngagementSourceTestData;

impl TestDataGenerator for EngagementSourceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ENGAGEMENTSOURCE API TEST
// ============================================================================

/// EngagementSource API test suite
pub struct EngagementSourceApiTest {
    inner: GenericCrudTest<EngagementSourceTestData>,
}

impl EngagementSourceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/engagement_sources", "EngagementSource");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EngagementSourceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EngagementSourceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_engagement_source_crud() {
        let mut test = EngagementSourceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EngagementSource specific tests here
// <<< CUSTOM TESTS END >>>
