//! GamificationGoal API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the GamificationGoal CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// GAMIFICATIONGOAL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for GamificationGoal
pub struct GamificationGoalTestData;

impl TestDataGenerator for GamificationGoalTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "definition_id": Uuid::new_v4().to_string(),
            "user_id": Uuid::new_v4().to_string(),
            "line_id": null,
            "challenge_id": null,
            "start_date": Utc::now().format("%Y-%m-%d").to_string(),
            "end_date": null,
            "target": 0,
            "current": 0,
            "state": "draft",
            "to_update": false,
            "last_update": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "definition_id": Uuid::new_v4().to_string(),
            "user_id": Uuid::new_v4().to_string(),
            "line_id": null,
            "challenge_id": null,
            "start_date": Utc::now().format("%Y-%m-%d").to_string(),
            "end_date": null,
            "target": 0,
            "current": 0,
            "state": "draft",
            "to_update": false,
            "last_update": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// GAMIFICATIONGOAL API TEST
// ============================================================================

/// GamificationGoal API test suite
pub struct GamificationGoalApiTest {
    inner: GenericCrudTest<GamificationGoalTestData>,
}

impl GamificationGoalApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/gamification_goals", "GamificationGoal");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, GamificationGoalTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for GamificationGoalApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_gamification_goal_crud() {
        let mut test = GamificationGoalApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add GamificationGoal specific tests here
// <<< CUSTOM TESTS END >>>
