//! Engagement Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::EngagementLinkTrackerService;
use crate::application::service::EngagementLinkTrackerClickService;
use crate::application::service::EngagementCampaignService;
use crate::application::service::EngagementSourceService;
use crate::application::service::EngagementMediumService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// EngagementLinkTracker service
    pub engagement_link_tracker_service: Arc<EngagementLinkTrackerService>,
    /// EngagementLinkTrackerClick service
    pub engagement_link_tracker_click_service: Arc<EngagementLinkTrackerClickService>,
    /// EngagementCampaign service
    pub engagement_campaign_service: Arc<EngagementCampaignService>,
    /// EngagementSource service
    pub engagement_source_service: Arc<EngagementSourceService>,
    /// EngagementMedium service
    pub engagement_medium_service: Arc<EngagementMediumService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        engagement_link_tracker_service: Arc<EngagementLinkTrackerService>,
        engagement_link_tracker_click_service: Arc<EngagementLinkTrackerClickService>,
        engagement_campaign_service: Arc<EngagementCampaignService>,
        engagement_source_service: Arc<EngagementSourceService>,
        engagement_medium_service: Arc<EngagementMediumService>
    ) -> Self {
        Self {
            engagement_link_tracker_service,
            engagement_link_tracker_click_service,
            engagement_campaign_service,
            engagement_source_service,
            engagement_medium_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::EngagementModule) -> Self {
        Self {
            engagement_link_tracker_service: module.engagement_link_tracker_service.clone(),
            engagement_link_tracker_click_service: module.engagement_link_tracker_click_service.clone(),
            engagement_campaign_service: module.engagement_campaign_service.clone(),
            engagement_source_service: module.engagement_source_service.clone(),
            engagement_medium_service: module.engagement_medium_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    engagement_link_tracker_service: Option<Arc<EngagementLinkTrackerService>>,
    engagement_link_tracker_click_service: Option<Arc<EngagementLinkTrackerClickService>>,
    engagement_campaign_service: Option<Arc<EngagementCampaignService>>,
    engagement_source_service: Option<Arc<EngagementSourceService>>,
    engagement_medium_service: Option<Arc<EngagementMediumService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the EngagementLinkTracker service.
    pub fn with_engagement_link_tracker_service(mut self, service: Arc<EngagementLinkTrackerService>) -> Self {
        self.engagement_link_tracker_service = Some(service);
        self
    }

    /// Set the EngagementLinkTrackerClick service.
    pub fn with_engagement_link_tracker_click_service(mut self, service: Arc<EngagementLinkTrackerClickService>) -> Self {
        self.engagement_link_tracker_click_service = Some(service);
        self
    }

    /// Set the EngagementCampaign service.
    pub fn with_engagement_campaign_service(mut self, service: Arc<EngagementCampaignService>) -> Self {
        self.engagement_campaign_service = Some(service);
        self
    }

    /// Set the EngagementSource service.
    pub fn with_engagement_source_service(mut self, service: Arc<EngagementSourceService>) -> Self {
        self.engagement_source_service = Some(service);
        self
    }

    /// Set the EngagementMedium service.
    pub fn with_engagement_medium_service(mut self, service: Arc<EngagementMediumService>) -> Self {
        self.engagement_medium_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            engagement_link_tracker_service: self.engagement_link_tracker_service.expect("engagement_link_tracker_service is required"),
            engagement_link_tracker_click_service: self.engagement_link_tracker_click_service.expect("engagement_link_tracker_click_service is required"),
            engagement_campaign_service: self.engagement_campaign_service.expect("engagement_campaign_service is required"),
            engagement_source_service: self.engagement_source_service.expect("engagement_source_service is required"),
            engagement_medium_service: self.engagement_medium_service.expect("engagement_medium_service is required"),
        }
    }
}
