//! Public events for Engagement module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ENGAGEMENTLINKTRACKER EVENTS
// ============================================================================

/// Event published when a EngagementLinkTracker is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerCreatedEvent {
    pub id: EngagementLinkTrackerId,
    pub data: EngagementLinkTrackerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementLinkTracker is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerUpdatedEvent {
    pub id: EngagementLinkTrackerId,
    pub data: EngagementLinkTrackerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementLinkTracker is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerDeletedEvent {
    pub id: EngagementLinkTrackerId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ENGAGEMENTLINKTRACKERCLICK EVENTS
// ============================================================================

/// Event published when a EngagementLinkTrackerClick is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerClickCreatedEvent {
    pub id: EngagementLinkTrackerClickId,
    pub data: EngagementLinkTrackerClickDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementLinkTrackerClick is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerClickUpdatedEvent {
    pub id: EngagementLinkTrackerClickId,
    pub data: EngagementLinkTrackerClickDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementLinkTrackerClick is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerClickDeletedEvent {
    pub id: EngagementLinkTrackerClickId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ENGAGEMENTCAMPAIGN EVENTS
// ============================================================================

/// Event published when a EngagementCampaign is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementCampaignCreatedEvent {
    pub id: EngagementCampaignId,
    pub data: EngagementCampaignDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementCampaign is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementCampaignUpdatedEvent {
    pub id: EngagementCampaignId,
    pub data: EngagementCampaignDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementCampaign is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementCampaignDeletedEvent {
    pub id: EngagementCampaignId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ENGAGEMENTSOURCE EVENTS
// ============================================================================

/// Event published when a EngagementSource is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementSourceCreatedEvent {
    pub id: EngagementSourceId,
    pub data: EngagementSourceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementSource is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementSourceUpdatedEvent {
    pub id: EngagementSourceId,
    pub data: EngagementSourceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementSource is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementSourceDeletedEvent {
    pub id: EngagementSourceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ENGAGEMENTMEDIUM EVENTS
// ============================================================================

/// Event published when a EngagementMedium is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMediumCreatedEvent {
    pub id: EngagementMediumId,
    pub data: EngagementMediumDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementMedium is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMediumUpdatedEvent {
    pub id: EngagementMediumId,
    pub data: EngagementMediumDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EngagementMedium is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMediumDeletedEvent {
    pub id: EngagementMediumId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Engagement module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum EngagementEvent {
    EngagementLinkTrackerCreated(EngagementLinkTrackerCreatedEvent),
    EngagementLinkTrackerUpdated(EngagementLinkTrackerUpdatedEvent),
    EngagementLinkTrackerDeleted(EngagementLinkTrackerDeletedEvent),
    EngagementLinkTrackerClickCreated(EngagementLinkTrackerClickCreatedEvent),
    EngagementLinkTrackerClickUpdated(EngagementLinkTrackerClickUpdatedEvent),
    EngagementLinkTrackerClickDeleted(EngagementLinkTrackerClickDeletedEvent),
    EngagementCampaignCreated(EngagementCampaignCreatedEvent),
    EngagementCampaignUpdated(EngagementCampaignUpdatedEvent),
    EngagementCampaignDeleted(EngagementCampaignDeletedEvent),
    EngagementSourceCreated(EngagementSourceCreatedEvent),
    EngagementSourceUpdated(EngagementSourceUpdatedEvent),
    EngagementSourceDeleted(EngagementSourceDeletedEvent),
    EngagementMediumCreated(EngagementMediumCreatedEvent),
    EngagementMediumUpdated(EngagementMediumUpdatedEvent),
    EngagementMediumDeleted(EngagementMediumDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for EngagementEventMetadata {
    fn default() -> Self {
        Self {
            module: "engagement",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
