//! Engagement Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Engagement exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use engagement::exports::{EngagementLinkTrackerDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `EngagementLinkTrackerDto` - Data transfer object for EngagementLinkTracker
/// - `EngagementLinkTrackerSummary` - Summary view of EngagementLinkTracker
/// - `EngagementLinkTrackerId` - Type-safe ID wrapper
/// - `EngagementLinkTrackerClickDto` - Data transfer object for EngagementLinkTrackerClick
/// - `EngagementLinkTrackerClickSummary` - Summary view of EngagementLinkTrackerClick
/// - `EngagementLinkTrackerClickId` - Type-safe ID wrapper
/// - `EngagementCampaignDto` - Data transfer object for EngagementCampaign
/// - `EngagementCampaignSummary` - Summary view of EngagementCampaign
/// - `EngagementCampaignId` - Type-safe ID wrapper
/// - `EngagementSourceDto` - Data transfer object for EngagementSource
/// - `EngagementSourceSummary` - Summary view of EngagementSource
/// - `EngagementSourceId` - Type-safe ID wrapper
/// - `EngagementMediumDto` - Data transfer object for EngagementMedium
/// - `EngagementMediumSummary` - Summary view of EngagementMedium
/// - `EngagementMediumId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `EngagementLinkTrackerCreatedEvent` - Published when EngagementLinkTracker is created
/// - `EngagementLinkTrackerUpdatedEvent` - Published when EngagementLinkTracker is updated
/// - `EngagementLinkTrackerDeletedEvent` - Published when EngagementLinkTracker is deleted
/// - `EngagementLinkTrackerClickCreatedEvent` - Published when EngagementLinkTrackerClick is created
/// - `EngagementLinkTrackerClickUpdatedEvent` - Published when EngagementLinkTrackerClick is updated
/// - `EngagementLinkTrackerClickDeletedEvent` - Published when EngagementLinkTrackerClick is deleted
/// - `EngagementCampaignCreatedEvent` - Published when EngagementCampaign is created
/// - `EngagementCampaignUpdatedEvent` - Published when EngagementCampaign is updated
/// - `EngagementCampaignDeletedEvent` - Published when EngagementCampaign is deleted
/// - `EngagementSourceCreatedEvent` - Published when EngagementSource is created
/// - `EngagementSourceUpdatedEvent` - Published when EngagementSource is updated
/// - `EngagementSourceDeletedEvent` - Published when EngagementSource is deleted
/// - `EngagementMediumCreatedEvent` - Published when EngagementMedium is created
/// - `EngagementMediumUpdatedEvent` - Published when EngagementMedium is updated
/// - `EngagementMediumDeletedEvent` - Published when EngagementMedium is deleted
pub struct ExportSummary;
