//! Public types for Engagement module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use crate::domain::entity::*;

// ============================================================================
// ENGAGEMENTLINKTRACKER TYPES
// ============================================================================

/// Type-safe ID for EngagementLinkTracker
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EngagementLinkTrackerId(pub Uuid);

impl EngagementLinkTrackerId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EngagementLinkTrackerId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EngagementLinkTrackerId> for Uuid {
    fn from(id: EngagementLinkTrackerId) -> Self {
        id.0
    }
}

/// Data transfer object for EngagementLinkTracker
///
/// This is the public representation of EngagementLinkTracker for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerDto {
    pub id: EngagementLinkTrackerId,
    pub url: String,
    pub code: String,
    pub title: Option<String>,
    pub label: String,
    pub campaign_id: Option<Uuid>,
    pub medium_id: Option<Uuid>,
    pub source_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of EngagementLinkTracker for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerSummary {
    pub id: EngagementLinkTrackerId,
    pub title: Option<String>,
}

/// Reference to EngagementLinkTracker for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerRef {
    pub id: EngagementLinkTrackerId,
}

// ============================================================================
// ENGAGEMENTLINKTRACKERCLICK TYPES
// ============================================================================

/// Type-safe ID for EngagementLinkTrackerClick
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EngagementLinkTrackerClickId(pub Uuid);

impl EngagementLinkTrackerClickId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EngagementLinkTrackerClickId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EngagementLinkTrackerClickId> for Uuid {
    fn from(id: EngagementLinkTrackerClickId) -> Self {
        id.0
    }
}

/// Data transfer object for EngagementLinkTrackerClick
///
/// This is the public representation of EngagementLinkTrackerClick for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerClickDto {
    pub id: EngagementLinkTrackerClickId,
    pub link_id: Uuid,
    pub campaign_id: Option<Uuid>,
    pub ip: Option<String>,
    pub country_code: Option<String>,
    pub click_day: NaiveDate,
    pub dedup_key: String,
    pub metadata: serde_json::Value,
}

/// Summary view of EngagementLinkTrackerClick for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerClickSummary {
    pub id: EngagementLinkTrackerClickId,
}

/// Reference to EngagementLinkTrackerClick for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementLinkTrackerClickRef {
    pub id: EngagementLinkTrackerClickId,
}

// ============================================================================
// ENGAGEMENTCAMPAIGN TYPES
// ============================================================================

/// Type-safe ID for EngagementCampaign
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EngagementCampaignId(pub Uuid);

impl EngagementCampaignId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EngagementCampaignId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EngagementCampaignId> for Uuid {
    fn from(id: EngagementCampaignId) -> Self {
        id.0
    }
}

/// Data transfer object for EngagementCampaign
///
/// This is the public representation of EngagementCampaign for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementCampaignDto {
    pub id: EngagementCampaignId,
    pub name: String,
    pub title: String,
    pub active: bool,
    pub user_id: Option<Uuid>,
    pub is_auto_campaign: bool,
    pub color: Option<i32>,
    pub metadata: serde_json::Value,
}

/// Summary view of EngagementCampaign for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementCampaignSummary {
    pub id: EngagementCampaignId,
    pub name: String,
    pub title: String,
}

/// Reference to EngagementCampaign for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementCampaignRef {
    pub id: EngagementCampaignId,
}

// ============================================================================
// ENGAGEMENTSOURCE TYPES
// ============================================================================

/// Type-safe ID for EngagementSource
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EngagementSourceId(pub Uuid);

impl EngagementSourceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EngagementSourceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EngagementSourceId> for Uuid {
    fn from(id: EngagementSourceId) -> Self {
        id.0
    }
}

/// Data transfer object for EngagementSource
///
/// This is the public representation of EngagementSource for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementSourceDto {
    pub id: EngagementSourceId,
    pub name: String,
    pub active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of EngagementSource for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementSourceSummary {
    pub id: EngagementSourceId,
    pub name: String,
}

/// Reference to EngagementSource for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementSourceRef {
    pub id: EngagementSourceId,
}

// ============================================================================
// ENGAGEMENTMEDIUM TYPES
// ============================================================================

/// Type-safe ID for EngagementMedium
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EngagementMediumId(pub Uuid);

impl EngagementMediumId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EngagementMediumId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EngagementMediumId> for Uuid {
    fn from(id: EngagementMediumId) -> Self {
        id.0
    }
}

/// Data transfer object for EngagementMedium
///
/// This is the public representation of EngagementMedium for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMediumDto {
    pub id: EngagementMediumId,
    pub name: String,
    pub active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of EngagementMedium for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMediumSummary {
    pub id: EngagementMediumId,
    pub name: String,
}

/// Reference to EngagementMedium for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMediumRef {
    pub id: EngagementMediumId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
