//! Engagement Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::EngagementLinkTrackerService;
pub use application::service::EngagementLinkTrackerClickService;
pub use application::service::EngagementCampaignService;
pub use application::service::EngagementSourceService;
pub use application::service::EngagementMediumService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Engagement module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let engagement = EngagementModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = engagement.all_crud_routes();
/// ```
pub struct EngagementModule {
    pub(crate) engagement_link_tracker_service: Arc<EngagementLinkTrackerService>,
    pub(crate) engagement_link_tracker_click_service: Arc<EngagementLinkTrackerClickService>,
    pub(crate) engagement_campaign_service: Arc<EngagementCampaignService>,
    pub(crate) engagement_source_service: Arc<EngagementSourceService>,
    pub(crate) engagement_medium_service: Arc<EngagementMediumService>,
    // <<< CUSTOM FIELDS
    pub(crate) engagement_write_service: std::sync::Arc<
        application::service::engagement_write_service::EngagementWriteService,
    >,
    // END CUSTOM
}

impl EngagementModule {
    /// Create a new module builder
    pub fn builder() -> EngagementModuleBuilder {
        EngagementModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_engagement_link_tracker_routes,
            create_engagement_link_tracker_click_routes,
            create_engagement_campaign_routes,
            create_engagement_source_routes,
            create_engagement_medium_routes,
        };

        Router::new()
            .merge(create_engagement_link_tracker_routes(self.engagement_link_tracker_service.clone()))
            .merge(create_engagement_link_tracker_click_routes(self.engagement_link_tracker_click_service.clone()))
            .merge(create_engagement_campaign_routes(self.engagement_campaign_service.clone()))
            .merge(create_engagement_source_routes(self.engagement_source_service.clone()))
            .merge(create_engagement_medium_routes(self.engagement_medium_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_engagement_link_tracker_read_routes,
            create_engagement_link_tracker_click_read_routes,
            create_engagement_campaign_read_routes,
            create_engagement_source_read_routes,
            create_engagement_medium_read_routes,
        };

        Router::new()
            .merge(create_engagement_link_tracker_read_routes(self.engagement_link_tracker_service.clone()))
            .merge(create_engagement_link_tracker_click_read_routes(self.engagement_link_tracker_click_service.clone()))
            .merge(create_engagement_campaign_read_routes(self.engagement_campaign_service.clone()))
            .merge(create_engagement_source_read_routes(self.engagement_source_service.clone()))
            .merge(create_engagement_medium_read_routes(self.engagement_medium_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The validated write path (attribution find-or-create, tracker
    /// minting, the redirect resolver) — the service behind the guarded and
    /// public route groups.
    pub fn engagement_write_service(
        &self,
    ) -> &std::sync::Arc<application::service::engagement_write_service::EngagementWriteService> {
        &self.engagement_write_service
    }

    /// Guarded management composition: safe GETs + validated write seams, NO
    /// generic mutation. Mount behind the host's authenticated tree.
    pub fn guarded_routes(self: &Arc<Self>) -> Router {
        presentation::http::guarded_routes::composer(Arc::clone(self))
    }

    /// The PUBLIC short-link redirect (`GET /r/:code`) — a BARE, throttled
    /// mount (ADR-0019 action_link class). Mount at the site root so codes
    /// resolve as `/r/<code>`; never behind auth.
    pub fn redirect_routes(self: &Arc<Self>) -> Router {
        presentation::http::redirect_routes::composer().with_state(Arc::clone(self))
    }
    // END CUSTOM
}

/// Builder for EngagementModule
pub struct EngagementModuleBuilder {
    db_pool: Option<PgPool>,
}

impl EngagementModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<EngagementModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // EngagementLinkTracker service
        let engagement_link_tracker_repository = Arc::new(EngagementLinkTrackerRepository::new(db_pool.clone()));
        let engagement_link_tracker_service = Arc::new(EngagementLinkTrackerService::with_repository(engagement_link_tracker_repository.clone()));

        // EngagementLinkTrackerClick service
        let engagement_link_tracker_click_repository = Arc::new(EngagementLinkTrackerClickRepository::new(db_pool.clone()));
        let engagement_link_tracker_click_service = Arc::new(EngagementLinkTrackerClickService::with_repository(engagement_link_tracker_click_repository.clone()));

        // EngagementCampaign service
        let engagement_campaign_repository = Arc::new(EngagementCampaignRepository::new(db_pool.clone()));
        let engagement_campaign_service = Arc::new(EngagementCampaignService::with_repository(engagement_campaign_repository.clone()));

        // EngagementSource service
        let engagement_source_repository = Arc::new(EngagementSourceRepository::new(db_pool.clone()));
        let engagement_source_service = Arc::new(EngagementSourceService::with_repository(engagement_source_repository.clone()));

        // EngagementMedium service
        let engagement_medium_repository = Arc::new(EngagementMediumRepository::new(db_pool.clone()));
        let engagement_medium_service = Arc::new(EngagementMediumService::with_repository(engagement_medium_repository.clone()));

        // <<< CUSTOM
        let engagement_write_service = std::sync::Arc::new(
            application::service::engagement_write_service::EngagementWriteService::new(
                db_pool.clone(),
            ),
        );
        // END CUSTOM

        Ok(EngagementModule {
            engagement_link_tracker_service,
            engagement_link_tracker_click_service,
            engagement_campaign_service,
            engagement_source_service,
            engagement_medium_service,
            // <<< CUSTOM
            engagement_write_service,
            // END CUSTOM
        })
    }
}

impl Default for EngagementModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
