//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod engagement_link_tracker_handler;
pub mod engagement_link_tracker_click_handler;
pub mod engagement_campaign_handler;
pub mod engagement_source_handler;
pub mod engagement_medium_handler;

// <<< CUSTOM
// Hand-written route groups (user-owned; survive regen): the guarded
// management composition and the public /r/<code> redirect.
pub mod guarded_routes;
pub mod redirect_routes;
// END CUSTOM

// Re-exports
pub use engagement_link_tracker_handler::{create_engagement_link_tracker_routes, create_engagement_link_tracker_read_routes, create_engagement_link_tracker_write_routes};
pub use engagement_link_tracker_click_handler::{create_engagement_link_tracker_click_routes, create_engagement_link_tracker_click_read_routes, create_engagement_link_tracker_click_write_routes};
pub use engagement_campaign_handler::{create_engagement_campaign_routes, create_engagement_campaign_read_routes, create_engagement_campaign_write_routes};
pub use engagement_source_handler::{create_engagement_source_routes, create_engagement_source_read_routes, create_engagement_source_write_routes};
pub use engagement_medium_handler::{create_engagement_medium_routes, create_engagement_medium_read_routes, create_engagement_medium_write_routes};
// <<< CUSTOM
// END CUSTOM
